import {ALANLAR,TURLER,DURUMLAR,SEVIYELER,yetkili,bugun,kacis as e,sirala,sonAlanlar,oncelik,geciken,kayitDogrula,raporHTML} from './core.js';
export async function panelKur(root,api) {
  if(!yetkili(api.kullanici())){root.textContent='Bu alan yalnızca PDR ve yetkili yönetime açıktır.';return;}
  const css=new URL('./panel.css',import.meta.url).href;
  if(!document.querySelector('link[data-pdr-style]')){const l=document.createElement('link');l.rel='stylesheet';l.href=css;l.dataset.pdrStyle='';document.head.append(l);}
  root.classList.add('pdr-work');
  let data,secili=api.ogrenciId||'',sekme='ozet',arama='',sinif='',oncelikFiltre='',form=null,busy=false,mesaj='',reportDates={};
  const dispatch=(act)=>api.islem?.(act,secili);
  const option=(obj,val)=>Object.entries(obj).map(([k,v])=>`<option value="${e(k)}" ${k===val?'selected':''}>${e(v)}</option>`).join('');
  const gFor=id=>data.gozlemler.filter(x=>x.ogrenciId===id);
  const kFor=id=>data.kayitlar.filter(x=>x.ogrenciId===id);
  const tFor=id=>data.testler.filter(x=>x.ogrenciId===id);
  async function yukle(){
    root.innerHTML='<p role="status">PDR çalışma alanı yükleniyor…</p>';
    try{data=await api.yukle();if(!yetkili(api.kullanici()))throw new Error('Oturum yetkisi değişti.');if(!data.donem)throw new Error('Aktif dönem alınamadı.');
      const ids=new Set(data.ogrenciler.map(x=>x.id));
      data.gozlemler=sirala(data.gozlemler.filter(x=>ids.has(x.ogrenciId)&&(!x.donem||x.donem===data.donem)));
      data.testler=sirala(data.testler.filter(x=>ids.has(x.ogrenciId)&&(!x.donem||x.donem===data.donem)));
      data.kayitlar=sirala(data.kayitlar.filter(x=>ids.has(x.ogrenciId)&&x.donem===data.donem));
      if(!ids.has(secili))secili='';render();
    }catch(err){root.innerHTML=`<div class="error" role="alert">Kayıtlar yüklenemedi. Yetki veya bağlantı sorunu olabilir; bu durum “kayıt yok” anlamına gelmez.</div><button data-retry>Yeniden dene</button>`;root.querySelector('[data-retry]').onclick=yukle;console.warn('PDR yükleme',err.code||err.message);}
  }
  function studentList(){const filtered=data.ogrenciler.filter(o=>(!sinif||o.sinif===sinif)&&(!arama||o.ad.toLocaleLowerCase('tr').includes(arama.toLocaleLowerCase('tr')))&&(!oncelikFiltre||oncelik(gFor(o.id))===oncelikFiltre));return filtered.map(o=>`<button class="student" data-student="${e(o.id)}" aria-pressed="${o.id===secili}"><strong>${e(o.ad)}</strong><span class="muted">${e(o.sinif)} · ${e(SEVIYELER[oncelik(gFor(o.id))]||'Henüz gözlem yok')}</span>${kFor(o.id).some(k=>geciken(k))?'<br><span class="badge warning">Takip tarihi geçti</span>':''}</button>`).join('')||'<div class="empty">Filtreye uygun öğrenci yok.</div>';}
  function render(){
    const tumG=data.ogrenciler.map(o=>oncelik(gFor(o.id)));
    root.innerHTML=`<div class="hero"><span class="badge">${e(data.donem)} · PDR</span><h2>Rehberlik çalışma alanı</h2><p>Her çocuğun gelişimini gözlemle, destekle ve takip et.</p><div class="row">${[['duyurular','Duyurular'],['etkinlik','Etkinlikler'],['mesajlasma','Mesajlar'],['profilim','Özlük ve izinlerim'],['fis','Fiş ekle'],['ihtiyac','İhtiyaç bildir']].map(([id,ad])=>`<button data-action="${id}">${ad}</button>`).join('')}<button data-refresh>Yenile</button></div></div><div class="stats">${[[data.ogrenciler.length,'Aktif öğrenci'],[tumG.filter(x=>x==='takip').length,'Yakın takip'],[data.kayitlar.filter(x=>x.tur==='destek'&&x.durum!=='tamamlandi').length,'Açık destek planı'],[data.kayitlar.filter(x=>geciken(x)).length,'Takip tarihi geçen']].map(([n,ad])=>`<div class="stat"><b>${n}</b>${ad}</div>`).join('')}</div><div class="layout"><aside class="box"><h3>Öğrenciler</h3><label>Öğrenci ara<input data-search value="${e(arama)}" placeholder="Ad soyad"></label><label>Sınıf<select data-class>${option({'':'Tüm sınıflar',...Object.fromEntries([...new Set(data.ogrenciler.map(o=>o.sinif).filter(Boolean))].sort().map(s=>[s,s]))},sinif)}</select></label><label>Gözlem durumu<select data-priority>${option({'':'Tüm durumlar',...SEVIYELER,yok:'Henüz gözlem yok'},oncelikFiltre)}</select></label><div class="students">${studentList()}</div></aside><section data-detail></section></div>`;
    root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>dispatch(b.dataset.action));root.querySelector('[data-refresh]').onclick=yukle;
    root.querySelector('[data-search]').oninput=ev=>{arama=ev.target.value;listeYenile();};root.querySelector('[data-class]').onchange=ev=>{sinif=ev.target.value;listeYenile();};root.querySelector('[data-priority]').onchange=ev=>{oncelikFiltre=ev.target.value;listeYenile();};
    bindStudents();detail();
  }
  function listeYenile(){root.querySelector('.students').innerHTML=studentList();bindStudents();}
  function bindStudents(){root.querySelectorAll('[data-student]').forEach(b=>b.onclick=()=>{if(form&&!confirm('Kaydedilmemiş form kapansın mı?'))return;secili=b.dataset.student;form=null;mesaj='';listeYenile();detail();if(window.innerWidth<720)root.querySelector('[data-detail]').scrollIntoView({behavior:'smooth',block:'start'});});}
  function detail(){const host=root.querySelector('[data-detail]');const o=data.ogrenciler.find(x=>x.id===secili);
    if(!o){host.innerHTML=`<div class="box"><h3>Bugünün takipleri</h3><p class="muted">Öğrenci seçerek dosyasını açabilir, görüşme veya destek planı ekleyebilirsiniz.</p>${data.kayitlar.filter(k=>k.durum!=='tamamlandi'&&k.takipTarihi&&k.takipTarihi<=bugun()).map(k=>`<button data-open-student="${e(k.ogrenciId)}">${e(k.ogrenciAd)} · ${e(k.baslik)} · ${e(k.takipTarihi)}</button>`).join('')||'<p>Bugün için açık takip bulunmuyor.</p>'}</div>`;host.querySelectorAll('[data-open-student]').forEach(b=>b.onclick=()=>{secili=b.dataset.openStudent;render();});return;}
    host.innerHTML=`<div class="box"><h2>${e(o.ad)}</h2><p class="muted">${e(o.sinif)} · Öğrenci dosyası</p><div class="row"><button data-action="gozlem">Gözlem ekle</button><button data-action="test">Test sonucu ekle</button>${Object.entries(TURLER).map(([k,ad])=>`<button data-new="${k}">${ad} ekle</button>`).join('')}</div><nav role="tablist">${Object.entries({ozet:'Genel görünüm',gecmis:'Gözlem ve testler',takip:'Görüşme ve destek',rapor:'Rapor'}).map(([k,ad])=>`<button role="tab" aria-selected="${sekme===k}" data-tab="${k}">${ad}</button>`).join('')}</nav><p class="muted">Görüşme, destek planı ve dönem değerlendirmeleri kurum içidir; otomatik olarak veliye gönderilmez.</p><div role="status">${mesaj?`<p class="success">${e(mesaj)}</p>`:''}</div><div data-content></div></div>`;
    host.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>dispatch(b.dataset.action));host.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>{form={tur:b.dataset.new,tarih:bugun(),durum:'planlandi'};content(o);});host.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(form&&!confirm('Kaydedilmemiş form kapansın mı?'))return;form=null;sekme=b.dataset.tab;detail();});content(o);
  }
  function content(o){const host=root.querySelector('[data-content]');if(form){formRender(host,o);return;}
    const gs=gFor(o.id),ks=kFor(o.id),ts=tFor(o.id);
    if(sekme==='ozet'){const son=sonAlanlar(gs);host.innerHTML=`<div class="grid">${Object.entries(ALANLAR).map(([id,ad])=>`<article><h3>${ad}</h3><span class="badge">${e(SEVIYELER[son[id]?.seviye]||'Henüz gözlem yok')}</span><p class="muted">${e(son[id]?.tarih||'')}</p><p>${e(son[id]?.not||'')}</p></article>`).join('')}</div><p class="muted">Alanların en son gözlemleri gösterilir. Standart gelişim puanı veya tanı değildir.</p>`;}
    else if(sekme==='gecmis'){host.innerHTML=gs.map(g=>`<article><h3>${e(ALANLAR[g.alan]||g.alan)} · ${e(g.tarih)}</h3><span class="badge">${e(SEVIYELER[g.seviye]||g.seviye)}</span><p>${e(g.not)}</p><p class="muted">${e((g.oneriler||[]).join(' · '))}</p></article>`).join('')+ts.map(t=>`<article><h3>${e(t.testAd||t.testKod)} · ${e(t.tarih)}</h3><p>${e(t.ozet)}</p><p>${e(t.uzmanYorumu)}</p></article>`).join('')||'<p class="empty">Gözlem veya test kaydı yok.</p>';}
    else if(sekme==='takip'){host.innerHTML=ks.map(k=>`<article><span class="badge ${geciken(k)?'warning':''}">${e(TURLER[k.tur])} · ${e(DURUMLAR[k.durum])}</span><h3>${e(k.baslik)}</h3><p class="muted">${e(k.tarih)} · Takip: ${e(k.takipTarihi||'—')} · ${e(k.uzmanAd)}</p>${[['Özet','ozet'],['Katılımcılar','katilimcilar'],['Hedef','hedef'],['Uygulama','uygulama'],['Aile önerisi','aileOnerisi'],['Öğretmen önerisi','ogretmenOnerisi'],['Sonuç','sonuc']].map(([ad,key])=>k[key]?`<p><b>${ad}:</b> ${e(k[key])}</p>`:'').join('')}<button data-edit="${e(k.id)}">Güncelle / Sonuç ekle</button></article>`).join('')||'<p class="empty">Henüz görüşme veya destek planı yok.</p>';host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{form={...ks.find(k=>k.id===b.dataset.edit)};content(o);});}
    else{host.innerHTML=`<div class="grid"><label>Başlangıç<input type="date" data-from value="${e(reportDates.baslangic||'')}"></label><label>Bitiş<input type="date" data-to value="${e(reportDates.bitis||'')}"></label></div><div class="row"><button data-report>Raporu güncelle</button><button data-print>Yazdır / PDF olarak kaydet</button></div><div class="report">${raporHTML(o,gs,ts,ks,reportDates)}</div>`;host.querySelector('[data-report]').onclick=()=>{const from=host.querySelector('[data-from]').value,to=host.querySelector('[data-to]').value;if(from&&to&&from>to){alert('Başlangıç tarihi bitişten sonra olamaz.');return;}reportDates={baslangic:from,bitis:to};content(o);};host.querySelector('[data-print]').onclick=()=>{if(window.Capacitor?.isNativePlatform?.()){alert('Bu raporu PDF olarak almak veya yazdırmak için portalın PDR ekranını kullanın.');return;}window.print();};}
  }
  function formRender(host,o){const k=form;
    const field=(key,ad,required=false)=>`<label class="wide">${ad}${required?' *':''}<textarea name="${key}" rows="3" maxlength="5000" ${required?'required':''}>${e(k[key]||'')}</textarea></label>`;
    host.innerHTML=`<form><h3>${e(TURLER[k.tur])}</h3><div class="grid"><label class="wide">Başlık *<input name="baslik" maxlength="160" required value="${e(k.baslik||'')}"></label><label>Tarih *<input type="date" name="tarih" required value="${e(k.tarih)}"></label><label>Takip tarihi${k.tur==='destek'?' *':''}<input type="date" name="takipTarihi" ${k.tur==='destek'?'required':''} value="${e(k.takipTarihi||'')}"></label><label>Durum<select name="durum">${option(DURUMLAR,k.durum)}</select></label><label>Katılımcılar<input name="katilimcilar" maxlength="5000" value="${e(k.katilimcilar||'')}" placeholder="Çocuk, veli, öğretmen…"></label>${field('ozet',k.tur==='rapor'?'Gelişim özeti ve güçlü yönler':'Görüşme / ihtiyaç özeti',true)}${field('hedef','Gözlenebilir hedef',k.tur==='destek')}${field('uygulama','Uygulama, sıklık ve sorumlu kişi')}${field('aileOnerisi','Aileye önerilecek çalışmalar')}${field('ogretmenOnerisi','Öğretmene önerilecek sınıf düzenlemeleri')}${field('sonuc','İzlem sonucu ve sonraki adım')}</div><div data-error role="alert"></div><div class="row"><button class="primary" type="submit">Kaydet</button><button type="button" data-cancel>İptal</button></div></form>`;
    host.querySelector('[data-cancel]').onclick=()=>{form=null;content(o);};host.querySelector('form').onsubmit=async ev=>{ev.preventDefault();if(busy)return;let saved;const f=ev.target;try{const values=Object.fromEntries(new FormData(f));saved=kayitDogrula({...values,ogrenciId:o.id,tur:k.tur},data.ogrenciler,api.kullanici(),data.donem);busy=true;f.querySelectorAll('button').forEach(b=>b.disabled=true);await api.kaydet(saved,k.id||null);form=null;sekme='takip';mesaj='Kayıt kaydedildi.';await yukle();}catch(err){const box=host.querySelector('[data-error]');if(box){box.className='error';box.textContent=err.message||'Kayıt kaydedilemedi. Formunuz korunuyor.';}}finally{busy=false;f.querySelectorAll('button').forEach(b=>b.disabled=false);}};
  }
  await yukle();
}
