import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
const base=new URL(existsSync(new URL('../js/finans/core.js',import.meta.url))?'../js/finans/':'../www/js/finans/',import.meta.url);
const {bildirimiIsle,bildirimImzasi,planSatiriImzasi,hesapOku,hatirlatmaTaslagi,hatirlatmaGonder,gecerliDonem,veliAlicilari}=await import(new URL('payment-actions.js',base));
const {odemePlani}=await import(new URL('core.js',base));
const period='2026-2027';
const plan=()=>({anne:{adSoyad:'Demo Veli',eposta:'demo@example.invalid'},aidatAyarlari:{baslangicAyi:'2026-09',taksitSayisi:1,aylikAidat:33300,sonOdemeGunu:1},aylikOdemeler:{}});
const note=()=>({ogrenciId:'demo',kalemTipi:'aidat-2026-09',tutar:33300,odemeTarihi:'2026-09-17',durum:'bekliyor',veliEmail:'demo@example.invalid'});
function fixture(b=note(),v=plan()){
 const map=new Map([['ogrenciler/demo',{ogrenciAdSoyad:'Demo Öğrenci'}],['ogrenciler/demo/donemler/'+period,v],['odemeBildirimleri/n',b]]);let writes=0,mails=0,failCommit=false;
 const fb={doc:(_,...p)=>p.join('/'),collection:(_,...p)=>p.join('/'),where:(key,op,value)=>({key,value}),query:(path,...filters)=>({path,filters}),serverTimestamp:()=>new Date().toISOString(),
 getDoc:async ref=>({exists:()=>map.has(ref),data:()=>structuredClone(map.get(ref))}),
 getDocs:async ref=>{const path=typeof ref==='string'?ref:ref.path;return {docs:[...map].filter(([k,v])=>k.startsWith(path+'/')&&!k.slice(path.length+1).includes('/')&&(typeof ref==='string'||ref.filters.every(f=>v[f.key]===f.value))).map(([k,v])=>({id:k.split('/').at(-1),data:()=>structuredClone(v)}))};},
 runTransaction:async(_,fn)=>{const pending=[];let wrote=false;const result=await fn({get:async ref=>{assert.equal(wrote,false,'all reads before writes');return fb.getDoc(ref);},set:(r,u)=>{wrote=true;pending.push([r,u]);},update:(r,u)=>{wrote=true;pending.push([r,{...map.get(r),...u}]);}});if(failCommit)throw Error('commit failed');pending.forEach(([r,u])=>map.set(r,u));writes+=pending.length;return result;},
 addDoc:async(ref,data)=>{map.set(ref+'/log',data);return {id:'log'};}};
 const ctx={fb,db:{},email:'accountant@example.invalid',brevoMail:async()=>{mails++;return {success:true,messageId:'demo'};}};
 const args=()=>({id:'n',ogrenciId:'demo',donem:period,donemDogrulandi:true,imza:bildirimImzasi(map.get('odemeBildirimleri/n')),planImza:planSatiriImzasi(odemePlani(map.get('ogrenciler/demo/donemler/'+period)).satirlar[0])});
 return {ctx,map,args,get writes(){return writes;},get mails(){return mails;},set failCommit(v){failCommit=v;}};
}
test('legacy period repair and approval atomically update the exact 33300 payment',async()=>{
 const f=fixture();await bildirimiIsle(f.ctx,f.args());
 assert.equal(f.map.get('odemeBildirimleri/n').donem,period);assert.equal(f.map.get('odemeBildirimleri/n').durum,'onaylandi');
 assert.equal(f.map.get('ogrenciler/demo/donemler/'+period).aylikOdemeler['2026-09'].odenenTutar,33300);
 assert.equal(f.map.get('odemeler/bildirim_n').donemDogrulandi,true);assert.equal(f.writes,3);
});
test('missing period is never silently taken from the selected dashboard period',async()=>{
 const f=fixture();await assert.rejects(bildirimiIsle(f.ctx,{...f.args(),donemDogrulandi:false}),/işaretleyin/);assert.equal(f.writes,0);assert.equal(f.map.get('odemeBildirimleri/n').donem,undefined);
});
test('known period cannot be reassigned',async()=>{const f=fixture({...note(),donem:period});await assert.rejects(bildirimiIsle(f.ctx,{...f.args(),donem:'2025-2026'}),/farklı/);assert.equal(f.writes,0);});
test('unregistered period cannot create a new student term document',async()=>{const f=fixture();await assert.rejects(bildirimiIsle(f.ctx,{...f.args(),donem:'2025-2026'}),/bulunamadı/);assert.equal(f.writes,0);});
test('invalid and non-consecutive periods rejected',()=>{for(const s of ['',null,'2026-2028','2026/2027','26-27'])assert.equal(gecerliDonem(s),false);assert.equal(gecerliDonem(period),true);});
test('amount and student changes since review are rejected',async()=>{for(const change of [{tutar:10},{ogrenciId:'other'},{odemeTarihi:'2026-09-16'}]){const f=fixture(),args=f.args();Object.assign(f.map.get('odemeBildirimleri/n'),change);await assert.rejects(bildirimiIsle(f.ctx,args),/değişmiş/);assert.equal(f.writes,0);}});
test('balance change since preview forces a fresh review',async()=>{const f=fixture(),args=f.args();f.map.get('ogrenciler/demo/donemler/'+period).aylikOdemeler['2026-09']={odenenTutar:100};await assert.rejects(bildirimiIsle(f.ctx,args),/bakiye değişmiş/);assert.equal(f.writes,0);});
test('double approval cannot double count',async()=>{const f=fixture(),args=f.args();await bildirimiIsle(f.ctx,args);await assert.rejects(bildirimiIsle(f.ctx,args));assert.equal(f.writes,3);});
test('an existing audit blocks repeated posting even with stale pending status',async()=>{const f=fixture();f.map.set('odemeler/bildirim_n',{tutar:33300});await assert.rejects(bildirimiIsle(f.ctx,f.args()),/zaten var/);assert.equal(f.writes,0);});
test('existing source movement also blocks an inconsistent pending record',async()=>{const v=plan();v.aylikOdemeler['2026-09']={odenenTutar:1,hareketler:[{id:'n',tutar:1}]};const f=fixture(note(),v);await assert.rejects(bildirimiIsle(f.ctx,f.args()),/daha önce işlenmiş/);assert.equal(f.writes,0);});
test('rejecting a periodless notification does not assign a period or touch debt',async()=>{const f=fixture(),before=JSON.stringify(f.map.get('ogrenciler/demo/donemler/'+period));await bildirimiIsle(f.ctx,{...f.args(),donem:'',donemDogrulandi:false,sonuc:'ret'});assert.equal(f.map.get('odemeBildirimleri/n').durum,'reddedildi');assert.equal(f.map.get('odemeBildirimleri/n').donem,undefined);assert.equal(JSON.stringify(f.map.get('ogrenciler/demo/donemler/'+period)),before);assert.equal(f.writes,1);});
test('failed commit leaves period, debt and audit unchanged',async()=>{const f=fixture(),before=JSON.stringify([...f.map]);f.failCommit=true;await assert.rejects(bildirimiIsle(f.ctx,f.args()),/commit failed/);assert.equal(JSON.stringify([...f.map]),before);assert.equal(f.writes,0);});
test('invalid amounts and dates never write',async()=>{for(const patch of [{tutar:-1},{tutar:33301},{tutar:NaN},{odemeTarihi:''},{odemeTarihi:'2099-01-01'}]){const f=fixture({...note(),...patch});await assert.rejects(bildirimiIsle(f.ctx,f.args()));assert.equal(f.writes,0);}});
test('a different payment item cannot be inferred from description',async()=>{const f=fixture({...note(),kalemTipi:'aidat-2025-09',kalemAd:'Eylül 2026'});await assert.rejects(bildirimiIsle(f.ctx,f.args()));assert.equal(f.writes,0);});
test('account reader scopes notifications by student ID and selected period',async()=>{const f=fixture();f.map.set('odemeBildirimleri/other',{...note(),ogrenciId:'other'});f.map.set('odemeBildirimleri/past',{...note(),donem:'2025-2026'});const h=await hesapOku(f.ctx,'demo',period);assert.deepEqual(h.bildirimler.map(b=>b.id),['n']);assert.equal(f.writes,0);});
test('absent account or failed read is not shown as zero debt',async()=>{const f=fixture();f.map.delete('ogrenciler/demo');await assert.rejects(hesapOku(f.ctx,'demo',period));f.ctx.fb.getDocs=async()=>{throw Error('permission-denied');};await assert.rejects(hesapOku(f.ctx,'demo',period));});
test('parents are taken from the selected period and deduplicated, invalid mail is excluded',()=>{assert.deepEqual(veliAlicilari({anne:{eposta:'DEMO@EXAMPLE.INVALID'},baba:{email:'demo@example.invalid'},vasi:{eposta:'bad\nmail@example.invalid'}}).map(a=>a.email),['demo@example.invalid']);});
test('pending parent notification blocks reminder creation without sending email',async()=>{const f=fixture(),h=await hesapOku(f.ctx,'demo',period);assert.throws(()=>hatirlatmaTaslagi(h,'2026-09'),/bekleyen ödeme/);assert.equal(f.mails,0);});
test('periodless notification also blocks a reminder for a different installment',async()=>{const f=fixture();f.map.get('ogrenciler/demo/donemler/'+period).aidatAyarlari.taksitSayisi=2;const h=await hesapOku(f.ctx,'demo',period);assert.throws(()=>hatirlatmaTaslagi(h,'2026-10'),/bekleyen ödeme/);});
test('no reminder without explicit confirmation',async()=>{const f=fixture({...note(),durum:'reddedildi'}),t=hatirlatmaTaslagi(await hesapOku(f.ctx,'demo',period),'2026-09');await assert.rejects(hatirlatmaGonder(f.ctx,t,false));assert.equal(f.mails,0);});
test('new pending notice during preview blocks sending',async()=>{const f=fixture({...note(),durum:'reddedildi'}),t=hatirlatmaTaslagi(await hesapOku(f.ctx,'demo',period),'2026-09');f.map.set('odemeBildirimleri/new',note());await assert.rejects(hatirlatmaGonder(f.ctx,t,true),/bekleyen ödeme/);assert.equal(f.mails,0);});
test('changed balance or parent during preview blocks stale reminders',async()=>{for(const kind of ['amount','parent']){const f=fixture({...note(),durum:'reddedildi'}),t=hatirlatmaTaslagi(await hesapOku(f.ctx,'demo',period),'2026-09');if(kind==='amount')f.map.get('ogrenciler/demo/donemler/'+period).aylikOdemeler['2026-09']={odenenTutar:10};else f.map.get('ogrenciler/demo/donemler/'+period).anne.eposta='new@example.invalid';await assert.rejects(hatirlatmaGonder(f.ctx,t,true),/değişti/);assert.equal(f.mails,0);}});
test('successful reminder logs acceptance without touching payment records',async()=>{const f=fixture({...note(),durum:'reddedildi'}),before=JSON.stringify(f.map.get('ogrenciler/demo/donemler/'+period)),t=hatirlatmaTaslagi(await hesapOku(f.ctx,'demo',period),'2026-09');const result=await hatirlatmaGonder(f.ctx,t,true);assert.equal(result.logKaydedildi,true);assert.equal(f.mails,1);assert.equal(JSON.stringify(f.map.get('ogrenciler/demo/donemler/'+period)),before);assert.equal(f.map.get('mailLoglari/log').donem,period);});
test('log failure after mail acceptance is not misreported as unsent',async()=>{const f=fixture({...note(),durum:'reddedildi'}),t=hatirlatmaTaslagi(await hesapOku(f.ctx,'demo',period),'2026-09');f.ctx.fb.addDoc=async()=>{throw Error('denied');};const result=await hatirlatmaGonder(f.ctx,t,true);assert.equal(result.success,true);assert.equal(result.logKaydedildi,false);assert.equal(f.mails,1);});
test('paid and future installments are excluded from generic due reminders',async()=>{const f=fixture({...note(),durum:'reddedildi'}),h=await hesapOku(f.ctx,'demo',period);h.veri.aidatAyarlari.taksitSayisi=2;const t=hatirlatmaTaslagi(h,'',new Date('2026-09-23'));assert.deepEqual(t.rows.map(r=>r.id),['2026-09']);h.veri.aylikOdemeler['2026-09']={odenenTutar:33300};assert.throws(()=>hatirlatmaTaslagi(h,'',new Date('2026-09-23')));});
test('mail preview escapes student and line content',async()=>{const f=fixture({...note(),durum:'reddedildi'}),h=await hesapOku(f.ctx,'demo',period);h.ogrenci.ogrenciAdSoyad='<img src=x onerror=alert(1)>';const t=hatirlatmaTaslagi(h,'2026-09');assert.ok(!t.htmlContent.includes('<img'));assert.ok(t.htmlContent.includes('&lt;img'));});
