import assert from 'node:assert/strict';
import test from 'node:test';
import {startNotificationCenter} from '../js/portal-bildirim-merkezi.js';
const email='review@example.invalid';
const flush=()=>new Promise(r=>setImmediate(r));
function fixture(){let snapshot,error,writer=async()=>{};const writes=[];let observer=()=>{};const fb={collection:(_,...p)=>p.join('/'),where:(...p)=>p,query:(...p)=>p,doc:(_,...p)=>p.join('/'),updateDoc:(path,data)=>{writes.push({path,data});return writer(path,data);},onSnapshot:(_q,_o,next,err)=>{snapshot=next;error=err;return()=>{};}};let c; c=startNotificationCenter({fb,db:{},email,mounts:[],excludeFromCount:r=>c?.ownedTypes.has(r.tip),onStateChange:state=>observer(state)});const row=(id,event=id,extra={})=>({id,olayAnahtari:event,tip:'duyuru',aliciEmail:email,okundu:false,...extra});const feed=rows=>snapshot({metadata:{fromCache:false},forEach:fn=>rows.forEach(r=>fn({id:r.id,data:()=>r,metadata:{hasPendingWrites:false}}))});return {c,row,feed,writes,set writer(fn){writer=fn},set observer(fn){observer=fn},error:()=>error(Error('review'))};}

test('synchronous observer reentry returns the installed bulk promise and cannot start thread reads',async t=>{const f=fixture();t.after(()=>f.c.stop());f.feed([f.row('one')]);let nested;f.observer=state=>{if(state.markingAll){nested=f.c.markAllRead();f.c.markThreadRead('one');}};const work=f.c.markAllRead();assert.equal(nested,work);assert.equal((await work).status,'complete');assert.equal(f.writes.length,1);});

test('queued external callback for replaced event is not invoked; newer callback stays untouched',async t=>{const f=fixture();t.after(()=>f.c.stop());f.feed([]);let release;const waiting=new Promise(r=>release=r);let oldReads=0,newReads=0;f.c.setExternalItems('source',Array.from({length:9},(_,i)=>f.row(String(i),'old-'+i,{onRead:async()=>{oldReads++;await waiting;return true;}})));const work=f.c.markAllRead();await flush();assert.equal(oldReads,8);f.c.setExternalItems('source',[f.row('8','new-8',{onRead:async()=>{newReads++;return true;}})]);release();const result=await work;assert.equal(result.status,'partial');assert.equal(newReads,0);assert.equal(oldReads,8);assert.equal(f.c.getState().unreadCount,1);});

test('pending old callback rejection cannot flip newer read external event to unread',async t=>{const f=fixture();t.after(()=>f.c.stop());f.feed([]);let fail;const waiting=new Promise((_r,j)=>fail=j);f.c.setExternalItems('source',[f.row('same','old',{onRead:()=>waiting})]);const work=f.c.markAllRead();await flush();f.c.setExternalItems('source',[f.row('same','new',{okundu:true,onRead:async()=>true})]);fail(Error('old failure'));await work;assert.equal(f.c.getState().unreadCount,0);});

test('captured mirror remains visible while read-filtered source is removed and write is pending, then clears on success',async t=>{const f=fixture();t.after(()=>f.c.stop());f.c.ownedTypes.add('duyuru');f.feed([f.row('root','same')]);let release;const waiting=new Promise(r=>release=r);f.writer=()=>waiting;f.c.setExternalItems('source',[f.row('source','same',{onRead:async()=>{f.c.setExternalItems('source',[]);return true;}})]);const work=f.c.markAllRead();await flush();assert.equal(f.c.getState().unreadCount,1);release();assert.equal((await work).status,'complete');assert.equal(f.c.getState().unreadCount,0);});

test('500 distinct plus duplicate roots are persisted headlessly with a bounded write count',async t=>{const f=fixture();t.after(()=>f.c.stop());f.feed(Array.from({length:520},(_,i)=>f.row(String(i),i<20?'duplicate':'event-'+i)));assert.equal((await f.c.markAllRead()).status,'complete');assert.equal(f.writes.length,520);});

test('queued source losing onRead for same event must not report complete with unread rows',async t=>{const f=fixture();t.after(()=>f.c.stop());f.feed([]);let release;const waiting=new Promise(r=>release=r);const rows=Array.from({length:9},(_,i)=>f.row(String(i),'event-'+i,{onRead:async()=>{await waiting;return true;}}));f.c.setExternalItems('source',rows);const work=f.c.markAllRead();await flush();f.c.setExternalItems('source',rows.map(r=>r.id==='8'?{...r,onRead:undefined}:r));release();const result=await work;assert.equal(f.c.getState().unreadCount,1);assert.equal(result.status,'partial');assert.equal(result.failedCount,1);});

test('already-read hidden root does not remain pinned after source removal',async t=>{const f=fixture();t.after(()=>f.c.stop());f.c.ownedTypes.add('duyuru');f.feed([f.row('root','same')]);f.c.setExternalItems('source',[f.row('source','same',{onRead:async()=>{f.feed([f.row('root','same',{okundu:true})]);f.c.setExternalItems('source',[]);return true;}})]);assert.equal((await f.c.markAllRead()).status,'complete');assert.equal(f.c.getState().unreadCount,0);assert.equal(f.c.getState().itemCount,0);});
