import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {streamThumbnailUrl,mediaSources,downloadSource,renderMedia} from '../js/portal-galeri-medya.js';
const source=fs.readFileSync(new URL('../js/portal-galeri-medya.js',import.meta.url),'utf8').replace(/export /g,'');
const video={dosyaTipi:'video',streamLibraryId:'123456',streamVideoId:'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee',embedUrl:'https://iframe.mediadelivery.net/embed/123456/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee'};
class Element{constructor(tag,doc){this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.children=[];this.style={};this.events={};this.hidden=false;this.dataset={};this.className='';this.textContent='';}get parentNode(){return this.parent;}remove(){if(this.parent){this.parent.children=this.parent.children.filter(x=>x!==this);this.parent=null;}}append(...items){for(const x of items){x.remove();x.parent=this;this.children.push(x);}}prepend(x){x.remove();x.parent=this;this.children.unshift(x);}replaceChildren(...items){for(const x of this.children)x.parent=null;this.children=[];this.append(...items);}setAttribute(){}removeAttribute(key){if(key==='src')this.src='';}addEventListener(name,fn){this.events[name]=fn;}pause(){}load(){}}
async function fixture({status='error',thumbnail=false,extra={},fetchImpl}={}){let calls=0,next=0;const timers=new Map();const c={URL,Date,console,setTimeout:fn=>{timers.set(++next,fn);return next;},clearTimeout:id=>timers.delete(id),fetch:async()=>{calls++;if(fetchImpl)return fetchImpl();if(status==='error')throw Error('synthetic offline');return{ok:true,json:async()=>({video:{status,encodeProgress:status===3?100:20,availableResolutions:status===3?'720p':''}})};}};vm.createContext(c);vm.runInContext(source,c);const doc={createElement:tag=>new Element(tag,doc)},host=new Element('div',doc);const dispose=c.renderMedia(host,{...video,...extra},{thumbnail});await new Promise(setImmediate);return{host,dispose,timers,get calls(){return calls;},get iframe(){return host.children.find(x=>x.tagName==='IFRAME');},get status(){return host.children.find(x=>x.className==='pg-media-status');}};}
test('status endpoint outage never blocks supplied Bunny player or adds a second status panel',async()=>{const f=await fixture();assert.ok(f.iframe);assert.equal(f.timers.size,0);assert.equal(f.status?.hidden,true);});
test('stream thumbnail is visual-only and never calls status endpoint',async()=>{const f=await fixture({thumbnail:true,extra:{kucukResim:'https://example.invalid/cover.jpg'}});assert.equal(f.calls,0);assert.equal(f.host.children[0].className,'pg-video-thumbnail');assert.equal(f.host.children.some(x=>x.className==='pg-media-status'),false);});
test('confirmed processing and encoder failure remain explicit',async()=>{const p=await fixture({status:2});assert.equal(p.iframe,undefined);assert.match(p.status.textContent,/hazırlanıyor.*%20/);assert.equal(p.timers.size,1);p.dispose();const e=await fixture({status:5});assert.equal(e.iframe,undefined);assert.match(e.status.textContent,/yeniden yüklemesi/);});
test('ready response renders supplied player',async()=>{const f=await fixture({status:3});assert.ok(f.iframe);assert.equal(f.timers.size,0);});
test('status outage without playable source remains bounded and truthful',async()=>{const f=await fixture({extra:{embedUrl:''}});assert.equal(f.iframe,undefined);assert.match(f.status.textContent,/hazırlanıyor/);assert.equal(f.timers.size,1);});
test('Stream thumbnails still require explicit host or supplied thumbnail',()=>{assert.equal(streamThumbnailUrl(video),'');assert.equal(mediaSources(video).poster,'');assert.equal(streamThumbnailUrl({...video,streamCdnHost:'https://bad.invalid'}),'');assert.equal(streamThumbnailUrl({...video,streamCdnHost:'vz-known.b-cdn.net'}),`https://vz-known.b-cdn.net/${video.streamVideoId}/thumbnail.jpg`);assert.equal(mediaSources({...video,kucukResim:'https://example.invalid/provided.jpg'}).poster,'https://example.invalid/provided.jpg');});
test('Firebase legacy URL and download source remain unchanged',()=>{const url='https://firebasestorage.googleapis.com/v0/b/synthetic/o/movie.mp4?alt=media&token=synthetic';assert.deepEqual(mediaSources({dosyaTipi:'video',url}).direct,[url]);assert.equal(downloadSource({dosyaTipi:'video',url}),url);});
