import {kurus,esc,para,bugun} from './core.js';
import {toplam} from './data.js';
export function finansAnalizi(data,month,today=bugun()){
 const groups=new Map();const cash=data.gelirler.filter(r=>String(r.tarih).startsWith(month));
 cash.forEach(r=>{const key=r.kalemId||r.id,ad=/^\d{4}-\d{2}$/.test(key)?'Eğitim taksitleri':r.kalem||'Diğer tahsilat';groups.set(ad,(groups.get(ad)||0)+kurus(r.tutar));});
 const ages=[{ad:'1–30 gün',tutar:0},{ad:'31–60 gün',tutar:0},{ad:'61–90 gün',tutar:0},{ad:'90 günden fazla',tutar:0}];let missing=0;
 const midnight=Date.parse(today+'T00:00:00Z');
 data.satirlar.filter(r=>r.kalan>0).forEach(r=>{if(!r.vade){missing++;return;}const date=Date.parse(r.vade+'T00:00:00Z');if(!Number.isFinite(date)){missing++;return;}const days=Math.floor((midnight-date)/86400000);if(days<=0)return;const i=days<=30?0:days<=60?1:days<=90?2:3;ages[i].tutar+=kurus(r.kalan);});
 const [y,m]=month.split('-').map(Number);const months=Array.from({length:6},(_,i)=>new Date(Date.UTC(y,m-6+i,1)).toISOString().slice(0,7));
 const trend=months.map(ay=>({ay,tahsilat:toplam(data.gelirler.filter(r=>String(r.tarih).startsWith(ay)),'tutar'),gider:toplam(data.giderler.filter(r=>String(r.tarih).startsWith(ay)),'tutar')}));
 return {kalemler:[...groups].map(([ad,v])=>({ad,tutar:v/100})).sort((a,b)=>b.tutar-a.tutar),yas:ages.map(r=>({...r,tutar:r.tutar/100})),vadesiz:missing,trend};
}
export function grafikRaporlar(data,month){const a=finansAnalizi(data,month);const bars=rows=>{const max=Math.max(1,...rows.map(r=>Math.abs(r.tutar)));return rows.map(r=>`<div class="analytic-row"><div><span>${esc(r.ad)}</span><b>${para(r.tutar)}</b></div><div class="analytic-track"><i style="width:${Math.abs(r.tutar)/max*100}%;background:${r.tutar<0?'#ba6b24':'#387758'}"></i></div></div>`).join('')||'<p>Seçili ayda tahsilat yok.</p>';};
 const max=Math.max(1,...a.trend.flatMap(r=>[r.tahsilat,r.gider])),min=Math.min(0,...a.trend.flatMap(r=>[r.tahsilat,r.gider])),scale=150/(max-min),zero=20+max*scale;
 const chart=`<svg viewBox="0 0 720 220" role="img" aria-label="Son altı ayın öğrenci tahsilatları ve kayıtlı okul giderleri"><line x1="30" x2="690" y1="${zero}" y2="${zero}" stroke="#aabeb0"/>${a.trend.map((r,i)=>`<g><title>${r.ay}: tahsilat ${para(r.tahsilat)}, kayıtlı gider ${para(r.gider)}</title>${[['tahsilat','#387758'],['gider','#cb874c']].map(([k,color],j)=>`<rect x="${42+i*110+j*31}" y="${zero-Math.max(0,r[k])*scale}" width="28" height="${Math.abs(r[k])*scale}" fill="${color}"/>`).join('')}<text x="${42+i*110}" y="202" font-size="12">${r.ay}</text></g>`).join('')}</svg>`;
 return `<section class="section" data-section="reports"><h2>Tahsilat ve gider eğilimi</h2><p class="muted">Yeşil: seçili dönemin öğrenci tahsilatları · Turuncu: kayıtlı okul giderleri. Giderler ödeme durumu doğrulanmamış kayıtları da içerir; bu grafik kasa bakiyesi değildir.</p>${chart}<details><summary>Grafiğin sayısal değerleri</summary><div class="scroll"><table><thead><tr><th>Ay</th><th>Öğrenci tahsilatı</th><th>Kayıtlı gider</th></tr></thead><tbody>${a.trend.map(r=>`<tr><td>${r.ay}</td><td>${para(r.tahsilat)}</td><td>${para(r.gider)}</td></tr>`).join('')}</tbody></table></div></details></section><div class="charts" data-section="reports"><section class="section"><h2>Tahsilat hangi kalemlerden geliyor?</h2><p class="muted">${esc(month)} · İade ve düzeltmeler düşülmüş net tutarlar.</p>${bars(a.kalemler)}</section><section class="section"><h2>Gecikmiş alacakların yaşı</h2><p class="muted">${bugun()} itibarıyla · yalnız kalan borç.</p>${bars(a.yas)}${a.vadesiz?`<p>Vadesi eksik ${a.vadesiz} kalem yaşlandırmaya alınmadı.</p>`:''}</section></div><section class="section" data-section="panel"><h2>Bugünün mali öncelikleri</h2>${a.yas[2].tutar+a.yas[3].tutar>0?`<p>60 günü aşan <b>${para(a.yas[2].tutar+a.yas[3].tutar)}</b> alacağı öğrenci bazında inceleyin.</p>`:'<p>60 günü aşan, vadesi tanımlı açık alacak bulunmuyor.</p>'}${data.bildirimler.some(b=>['bekliyor','beklemede'].includes(b.durum))?'<p>Veli ödeme bildirimleri kontrol bekliyor; banka veya dekontla doğruladıktan sonra ilgili aya işleyin.</p>':''}${a.vadesiz?'<p>Vadesi eksik kalemleri tamamlayarak ödeme takvimini netleştirin.</p>':''}</section>`;
}
