import {esc,para,bugun,sirala,basabas,bildirimKalemi,tahsilatiGeriAl} from './core.js';
import {okulVerisi,toplam,onayla} from './data.js';
const STATUS={odendi:'Ödendi',kismi:'Kısmen ödendi',gecikmis:'Gecikti',bekliyor:'Bekliyor',tanimsiz:'Tanımlanmamış'};
export async function dashboard(root,ctx){
 root.classList.add('finans-app');let data,tab=ctx.initialTab||'cari',sort='ogrenci',direction='asc',search='',status='',sinif='',month=bugun().slice(0,7),period=ctx.donem;
 root.innerHTML='<p>Finans kayıtları yükleniyor…</p>';
 async function load(){root.setAttribute('aria-busy','true');try{data=await okulVerisi({...ctx,donem:period});render();}catch(e){root.innerHTML=`<div class="error">Finans kayıtları okunamadı. Özet hesaplanmadı.<p>${esc(e.message)}</p><button id="retry">Yeniden dene</button></div>`;root.querySelector('#retry').onclick=load;}finally{root.removeAttribute('aria-busy');}}
 function card(title,value,filter){return `<button class="card" data-card="${filter}">${title}<strong>${esc(value)}</strong></button>`;}
 function bars(rows){const max=Math.max(1,...rows.map(r=>r.tutar));return rows.length?rows.map(r=>`<div class="bar"><span>${esc(r.ad)}</span><i style="width:${r.tutar/max*40}%"></i><b>${para(r.tutar)}</b></div>`).join(''):'<p>Seçili ayda kayıt bulunmuyor.</p>';}
 function filtered(){let rows=tab==='gider'?data.giderler.filter(r=>String(r.tarih||'').startsWith(month)).map(r=>({...r,kalem:r.baslik||r.aciklama||r.kategori,odenen:r.odendi===false?0:Number(r.tutar),durum:r.odendi===false?'bekliyor':'odendi'})):tab==='tahsilat'?data.gelirler.filter(r=>String(r.tarih||'').startsWith(month)):data.satirlar;
 return sirala(rows.filter(r=>(!search||[r.ogrenci,r.veli,r.kalem,r.sinif,r.kategori].join(' ').toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr')))&&(!sinif||r.sinif===sinif)&&(!status||(status==='gecikmis'?r.gecikmis:status==='acik'?r.kalan>0:r.durum===status))),sort,direction);}
 function columns(){return tab==='gider'?[['tarih','Tarih'],['kalem','Gider'],['kategori','Kategori'],['tutar','Tutar'],['durum','Durum']]:tab==='tahsilat'?[['tarih','Tahsilat tarihi'],['ogrenci','Öğrenci'],['kalem','Ait olduğu ay / kalem'],['tutar','Tahsilat'],['yontem','Yöntem']]:[['ogrenci','Öğrenci'],['sinif','Sınıf'],['kalem','Ay / kalem'],['vade','Son ödeme'],['beklenen','Borç'],['odenen','Ödenen'],['kalan','Kalan'],['durum','Durum']];}
 function cell(r,k){return ['tutar','beklenen','odenen','kalan'].includes(k)?para(r[k]):k==='durum'?`<span class="badge ${r.gecikmis?'turuncu':r.durum==='odendi'?'yesil':''}">${esc(STATUS[r.durum]||r.durum)}${r.gecikmis&&r.durum==='kismi'?' · gecikti':''}</span>`:esc(r[k]||'—');}
 function table(){const rows=filtered(),cols=columns();root.querySelector('#list').innerHTML=`<div class="muted">${rows.length} kayıt · ${tab==='tahsilat'?'Tahsilat: '+para(toplam(rows,'tutar')):tab==='gider'?'Gider: '+para(toplam(rows,'tutar')):'Kalan: '+para(toplam(rows,'kalan'))}</div><div class="scroll"><table><thead><tr>${cols.map(([k,t])=>`<th><button data-sort="${k}">${t} ${sort===k?(direction==='asc'?'↑':'↓'):'↕'}</button></th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(([k])=>`<td>${cell(r,k)}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${cols.length}">Eşleşen kayıt bulunamadı.</td></tr>`}</tbody></table></div>`;root.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{direction=sort===b.dataset.sort&&direction==='asc'?'desc':'asc';sort=b.dataset.sort;table();});}
 function render(){
 const due=data.satirlar.filter(r=>r.id===month),late=data.satirlar.filter(r=>r.gecikmis),cash=data.gelirler.filter(r=>String(r.tarih).startsWith(month)),expenses=data.giderler.filter(r=>String(r.tarih||'').startsWith(month));
 const pending=data.bildirimler.filter(b=>['bekliyor','beklemede'].includes(b.durum));
 const groups={};expenses.forEach(r=>{const k=r.kategori||'Sınıflandırılmamış';groups[k]=(groups[k]||0)+Number(r.tutar||0);});
 const fixed=expenses.filter(r=>r.tip==='sabit'),variable=expenses.filter(r=>r.tip==='degisken'),unclassified=expenses.filter(r=>!['sabit','degisken'].includes(r.tip));
 const enrolled=new Set(due.filter(r=>r.beklenen>0).map(r=>r.ogrenciId)).size;
 const be=unclassified.length||!expenses.length?{hazir:false,neden:'Başabaş için ayın giderlerini sabit / değişken olarak tamamlayın.'}:basabas({sabit:toplam(fixed,'tutar'),degisken:toplam(variable,'tutar'),ogrenci:enrolled,aylikGelir:toplam(due,'beklenen')});
 root.innerHTML=`<header><div class="muted">BİR ÇİÇEK KOLEJİ · FİNANS</div><h1>Muhasebe çalışma alanı</h1><p class="muted">${esc(period)} · Öğrenci ödeme planları ve tahsilatlar · Güncelleme: ${esc(new Date().toLocaleTimeString('tr-TR'))}</p></header>
 <div class="toolbar"><label>Dönem<input id="period" value="${esc(period)}" pattern="[0-9]{4}-[0-9]{4}" size="10"></label><label>Ay<input id="month" type="month" value="${month}"></label><button id="refresh" class="primary">Yenile</button><button id="print">Yazdır / PDF</button></div>
 ${data.ogrenciler.some(o=>o.plan.uyarilar?.length)?`<div class="error"><b>Mutabakat gereken kayıtlar</b>${data.ogrenciler.flatMap(o=>(o.plan.uyarilar||[]).map(x=>`<p>${esc(o.ad)} · ${esc(x)}</p>`)).join('')}</div>`:''}<div class="cards">${card('Bu ay planlanan',para(toplam(due,'beklenen')),'cari')}${card('Bu ay tahsil edilen',para(toplam(cash,'tutar')),'tahsilat')}${card('Gecikmiş alacak',para(toplam(late,'kalan')),'gecikmis')}${card('Onay bekleyen',pending.length+' bildirim','onay')}${card('Bu ay kayıtlı gider',para(toplam(expenses,'tutar')),'gider')}${card('Dönem kalan alacak',para(toplam(data.satirlar,'kalan')),'acik')}</div>
 <div class="charts"><section class="section"><h2>Giderlerin dağılımı</h2>${bars(Object.entries(groups).map(([ad,tutar])=>({ad,tutar})).sort((a,b)=>b.tutar-a.tutar))}</section><section class="section"><h2>Başabaş senaryosu</h2>${be.hazir?`<strong>${be.adet} öğrenci</strong><p>${enrolled} öğrencinin bu ayki eğitim planı ve girilmiş giderler esas alınır.</p><label>Öğrenci sayısı<input type="number" id="scenario" min="0" value="${enrolled}"></label><p id="scenarioResult"></p><small>Gider kayıtlarının tamamlığı sonucu etkiler. Bu bir senaryodur; gerçekleşen kâr değildir.</small>`:`<p>${esc(be.neden)}</p>`}</section></div>
 <section class="section"><h2>Aylık tahsilat ve ödeme planı</h2>${chart()}${trend()}</section>
 <section class="section" id="approvals"><h2>Ödeme bildirimleri</h2>${pending.map(b=>`<div class="payment card"><div><b>${esc(b.ogrenciAd)}</b><small>${esc(b.kalemAd||b.ayAd||bildirimKalemi(b))} · ${para(b.bildirilenTutar??b.tutar)} · ${esc(b.odemeTarihi||'Tarih eksik')}</small><small>${esc(b.not||'')}</small>${!b.donem?'<small class="error">Dönem eksik: işlemden önce kayıt dönemi doğrulanmalı.</small>':''}</div><button data-review="${esc(b.id)}">İncele</button></div>`).join('')||'<p>Bekleyen bildirim yok.</p>'}</section>
 <section class="section"><h2>İşlenmiş bildirimler</h2><p class="muted">İade veya hatalı onay düzeltmesi kayıt silmeden ters hareket oluşturur. Para transferi yapmaz.</p><div class="toolbar"><input id="historySearch" placeholder="Öğrenci veya kalem ara"><select id="historySort"><option value="date-desc">Tarih · yeniden eskiye</option><option value="date-asc">Tarih · eskiden yeniye</option><option value="name-asc">Öğrenci · A–Z</option><option value="name-desc">Öğrenci · Z–A</option><option value="amount-desc">Tutar · büyükten küçüğe</option><option value="amount-asc">Tutar · küçükten büyüğe</option></select></div><div id="history"></div></section><section class="section"><div class="toolbar"><button data-tab="cari">Öğrenci carileri</button><button data-tab="tahsilat">Tahsilatlar</button><button data-tab="gider">Giderler</button><button id="matrix">Aylık toplu rapor</button><button id="csv">CSV indir</button></div><div class="toolbar"><input id="search" placeholder="Öğrenci, veli veya kalem ara" value="${esc(search)}"><select id="status"><option value="">Tüm durumlar</option value="acik">Açık borçlar</option value="gecikmis">Gecikenler</option value="kismi">Kısmi ödemeler</option value="odendi">Ödenenler</option></select><select id="class"><option value="">Tüm sınıflar</option>${[...new Set(data.ogrenciler.map(o=>o.sinif))].filter(Boolean).sort().map(s=>`<option>${esc(s)}</option>`).join('')}</select></div><div id="list"></div></section>
 <p class="muted">Tarihsiz eski tahsilatlar aylık nakit grafiğine eklenmez (${data.gelirler.filter(r=>!r.tarih).length} kayıt). Geçmiş borçlar için ilgili dönemi seçebilirsiniz. Gider toplamı, ödeme durumu henüz doğrulanmamış kayıtları da kapsar.</p>`;
 history();root.querySelector('#historySearch').oninput=history;root.querySelector('#historySort').onchange=history;
 table();root.querySelector('#status').value=status;root.querySelector('#class').value=sinif;
 root.querySelector('#search').oninput=e=>{search=e.target.value;table();};root.querySelector('#status').onchange=e=>{status=e.target.value;table();};root.querySelector('#class').onchange=e=>{sinif=e.target.value;table();};
 root.querySelector('#refresh').onclick=()=>{const p=root.querySelector('#period').value;if(!/^\d{4}-\d{4}$/.test(p))return alert('Dönemi 2026-2027 biçiminde girin.');period=p;month=root.querySelector('#month').value||bugun().slice(0,7);load();};root.querySelector('#month').onchange=e=>{month=e.target.value;render();};
 root.querySelector('#print').onclick=()=>window.print();root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;status='';sinif='';root.querySelector('#status').value='';root.querySelector('#class').value='';sort=tab==='cari'?'ogrenci':'tarih';direction='asc';table();});
 root.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>{const t=b.dataset.card;if(t==='onay'){root.querySelector('#approvals').scrollIntoView();return;}tab=['gider','tahsilat'].includes(t)?t:'cari';status=['acik','gecikmis'].includes(t)?t:'';root.querySelector('#status').value=status;table();root.querySelector('#list').scrollIntoView();});
 root.querySelector('#csv').onclick=()=>download(filtered(),columns());root.querySelector('#matrix').onclick=matrix;
 root.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>review(b.dataset.review));
 if(be.hazir){const calc=()=>{const n=Number(root.querySelector('#scenario').value);root.querySelector('#scenarioResult').textContent='Tahmini aylık faaliyet sonucu: '+para(n*be.katki-toplam(fixed,'tutar'));};root.querySelector('#scenario').oninput=calc;calc();}
 }
 function chart(){
 const months=[...new Set(data.satirlar.map(r=>r.id).filter(k=>/^\d{4}-\d{2}$/.test(k)))].sort();
 if(!months.length)return '';
 const vals=months.map(m=>({m,plan:toplam(data.satirlar.filter(r=>r.id===m),'beklenen'),cash:toplam(data.gelirler.filter(r=>String(r.tarih).startsWith(m)),'tutar')}));
 const max=Math.max(1,...vals.flatMap(r=>[r.plan,r.cash])),min=Math.min(0,...vals.map(r=>r.cash)),scale=150/(max-min),zero=25+max*scale,slot=660/months.length;
 return `<p class="muted">Açık yeşil: aylık plan · Koyu yeşil: net tahsilat · Turuncu: net ters kayıt</p><svg viewBox="0 0 720 220" role="img" aria-label="Aylık ödeme planı ve gerçekleşen tahsilat karşılaştırması"><line x1="40" y1="${zero}" x2="710" y2="${zero}" stroke="#b9cec0"/>${vals.map((r,i)=>{const x=45+i*slot,w=slot*.32;return `<g><title>${r.m}: plan ${para(r.plan)}, tahsilat ${para(r.cash)}</title><rect x="${x}" y="${zero-r.plan*scale}" width="${w}" height="${r.plan*scale}" fill="#b6d9c2"/><rect x="${x+w}" y="${zero-Math.max(0,r.cash)*scale}" width="${w}" height="${Math.abs(r.cash)*scale}" fill="${r.cash<0?'#c87828':'#245840'}"/><text x="${x}" y="200" font-size="10">${r.m.slice(2)}</text></g>`;}).join('')}</svg>`;
 }
 function trend(){const months=[...new Set(data.satirlar.map(r=>r.id).filter(k=>/^\d{4}-\d{2}$/.test(k)))].sort();return `<div class="scroll"><table><thead><tr><th>Ay</th><th>Planlanan</th><th>O aya işlenen</th><th>Kalan</th><th>Ay içinde tahsil</th></tr></thead><tbody>${months.map(m=>{const r=data.satirlar.filter(r=>r.id===m);return `<tr><td>${esc(m)}</td><td>${para(toplam(r,'beklenen'))}</td><td>${para(toplam(r,'odenen'))}</td><td>${para(toplam(r,'kalan'))}</td><td>${para(toplam(data.gelirler.filter(g=>String(g.tarih).startsWith(m)),'tutar'))}</td></tr>`;}).join('')}</tbody></table></div>`;}
 function matrix(){const months=[...new Set(data.satirlar.map(r=>r.id).filter(k=>/^\d{4}-\d{2}$/.test(k)))].sort(),rows=data.ogrenciler.map(o=>({ogrenci:o.ad,sinif:o.sinif,...Object.fromEntries(months.map(m=>[m,o.plan.satirlar.find(r=>r.id===m)?.kalan??0]))}));download(sirala(rows,'ogrenci'),[['ogrenci','Öğrenci'],['sinif','Sınıf'],...months.map(m=>[m,m+' kalan'])]);}
 function download(rows,cols){const quote=v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"';const csv='\uFEFF'+[cols.map(c=>quote(c[1])).join(';'),...rows.map(r=>cols.map(([k])=>quote(r[k])).join(';'))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`BirCicek-${tab}-${period}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function history(){
  const term=root.querySelector('#historySearch').value.toLocaleLowerCase('tr'),[key,dir]=root.querySelector('#historySort').value.split('-');
  const rows=data.bildirimler.filter(b=>!['bekliyor','beklemede'].includes(b.durum)).map(b=>({...b,name:b.ogrenciAd||'',date:b.odemeTarihi||'',amount:Number(b.bildirilenTutar??b.tutar)||0})).filter(b=>[b.name,b.kalemAd||b.ayAd||bildirimKalemi(b)].join(' ').toLocaleLowerCase('tr').includes(term));
  const labels={onaylandi:'Onaylandı',onayli:'Onaylandı',reddedildi:'Reddedildi',ret:'Reddedildi',iade_edildi:'İade kaydedildi',geri_alindi:'Hatalı onay geri alındı'};
  root.querySelector('#history').innerHTML=sirala(rows,key,dir).map(b=>`<div class="payment card"><div><b>${esc(b.name)}</b><small>${esc(b.kalemAd||b.ayAd||bildirimKalemi(b))} · ${para(b.amount)} · ${esc(b.date)}</small><small>${esc(labels[b.durum]||b.durum)}</small></div>${b.durum==='onaylandi'&&b.tahsilatIslendi?`<button data-reverse="${esc(b.id)}">İade / düzeltme</button>`:''}</div>`).join('')||'<p>İşlenmiş bildirim bulunmuyor.</p>';
  root.querySelectorAll('[data-reverse]').forEach(b=>b.onclick=()=>reverse(b.dataset.reverse));
 }
 function reverse(id){
  const b=data.bildirimler.find(b=>b.id===id),d=document.createElement('dialog');
  d.innerHTML=`<h2>Tahsilat iadesi / düzeltmesi</h2><p>${esc(b.ogrenciAd)} · ${esc(b.kalemAd||bildirimKalemi(b))} · ${para(b.bildirilenTutar??b.tutar)}</p><p>Bu tahsilatın tamamı ters kayıtla geri alınır ve ilgili borç yeniden açılır. İşlem para transferi yapmaz. Kısmi iade için bu işlem kullanılmamalıdır.</p><form><label>İşlem<select name="type"><option value="duzeltme">Hatalı onayı düzelt</option><option value="iade">Yapılmış tam iadeyi kaydet</option></select></label><label>İşlem tarihi<input name="date" type="date" min="${esc(b.odemeTarihi)}" max="${bugun()}" value="${bugun()}" required></label><label>Açıklama<textarea name="reason" minlength="5" maxlength="1000" required></textarea></label><label><input name="confirm" type="checkbox" required> Tutarı ve borcun yeniden açılacağını kontrol ettim.</label><p class="error" hidden></p><div class="toolbar"><button type="submit">Ters kaydı oluştur</button><button type="button" id="cancel">Vazgeç</button></div></form>`;
  root.append(d);d.showModal();d.onclose=()=>d.remove();d.querySelector('#cancel').onclick=()=>d.close();
  d.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);d.querySelectorAll('button').forEach(b=>b.disabled=true);try{await tahsilatiGeriAl({...ctx,id,tarih:f.get('date'),neden:f.get('reason'),tur:f.get('type')});d.close();await load();}catch(err){const error=d.querySelector('.error');error.hidden=false;error.textContent=err.message;d.querySelectorAll('button').forEach(b=>b.disabled=false);}};
 }
 function review(id){const b=data.bildirimler.find(x=>x.id===id),row=data.satirlar.find(r=>r.ogrenciId===b.ogrenciId&&r.id===bildirimKalemi(b)),d=document.createElement('dialog');d.innerHTML=`<h2>Ödeme kontrolü</h2><p>${esc(b.ogrenciAd)} · ${esc(b.kalemAd||b.ayAd||bildirimKalemi(b))}</p><strong>${para(b.bildirilenTutar??b.tutar)}</strong><p>${esc(b.odemeTarihi||'Ödeme tarihi eksik')} · ${esc(b.odemeYontemi||b.yontem||'')}</p><p>${esc(b.not||'')}</p><p>${row?`Plandaki borç: ${para(row.beklenen)} · Önceden ödenen: ${para(row.odenen)} · Kalan: ${para(row.kalan)}`:'Ödeme planında eşleşen kalem bulunamadı.'}</p><p>Onay, belirtilen ayın veya kalemin kalan borcuna işlenir.</p><p class="error" id="reviewError" hidden></p><div class="toolbar"><button id="approve" class="primary">Tahsilatı doğrula</button><button id="reject">Reddet</button><button id="close">Kapat</button></div>`;root.append(d);d.showModal();d.querySelector('#close').onclick=()=>d.close();d.onclose=()=>d.remove();async function act(result){d.querySelectorAll('button').forEach(x=>x.disabled=true);try{if(!b.donem)throw Error('Eski bildirimin dönemini önce doğrulayıp kayda ekleyin. Otomatik dönem atanmadı.');await onayla({...ctx,id,email:ctx.email,donem:period,sonuc:result});d.close();await load();}catch(e){const err=d.querySelector('#reviewError');err.hidden=false;err.textContent=e.message;d.querySelectorAll('button').forEach(x=>x.disabled=false);}}d.querySelector('#approve').onclick=()=>act('onayli');d.querySelector('#reject').onclick=()=>act('ret');}
 await load();
}
