import {hesapAc,odemeKontrolAc,benzerBildirimler,benzerBildirimUyarisi} from './payment-workspace.js';
import {grafikRaporlar} from './analytics.js';
import {mutabakatEkrani} from './reconciliation.js';
import {dekontIndir} from './receipts.js';
import {esc,para,bugun,sirala,basabas,bildirimKalemi,tahsilatiGeriAl} from './core.js';
import {okulVerisi,toplam,onayla} from './data.js';
const STATUS={odendi:'Ödendi',kismi:'Kısmen ödendi',gecikmis:'Gecikti',bekliyor:'Bekliyor',tanimsiz:'Tanımlanmamış'};
export function cariOzetleri(data,month){return data.ogrenciler.map(o=>{const rows=o.plan.satirlar;return {ogrenciId:o.id,ogrenci:o.ad,veli:o.veli,sinif:o.sinif,beklenen:o.plan.toplam,odenen:o.plan.odenen,kalan:o.plan.kalan,geciken:o.plan.geciken,buay:toplam(rows.filter(r=>String(r.vade).startsWith(month)),'kalan'),gecikmis:o.plan.geciken>0,durum:o.plan.plansiz||!o.plan.toplam?'tanimsiz':!o.plan.kalan?'odendi':o.plan.odenen>0?'kismi':o.plan.geciken>0?'gecikmis':'bekliyor'};});}
export async function dashboard(root,ctx){
 root.classList.add('finans-app');let data,tab=ctx.initialTab||'cari',sort='ogrenci',direction='asc',search='',status='',sinif='',month=bugun().slice(0,7),period=ctx.donem,page=1,pageSize=25,view=['gider','tahsilat'].includes(ctx.initialTab)?'accounts':'panel';
 root.innerHTML='<p>Finans kayıtları yükleniyor…</p>';
 async function load(){root.setAttribute('aria-busy','true');ctx.onLoading?.();try{data=await okulVerisi({...ctx,donem:period});render();ctx.onData?.(data);}catch(e){ctx.onError?.(e);root.innerHTML=`<div class="error">Finans kayıtları okunamadı. Özet hesaplanmadı.<p>${esc(e.message)}</p><button id="retry">Yeniden dene</button></div>`;root.querySelector('#retry').onclick=load;}finally{root.removeAttribute('aria-busy');}}
 function card(title,value,filter){return `<button class="card" data-card="${filter}">${title}<strong>${esc(value)}</strong></button>`;}
 function bars(rows){const max=Math.max(1,...rows.map(r=>r.tutar));return rows.length?rows.map(r=>`<div class="bar"><span>${esc(r.ad)}</span><i style="width:${r.tutar/max*40}%"></i><b>${para(r.tutar)}</b></div>`).join(''):'<p>Seçili ayda kayıt bulunmuyor.</p>';}
 function cariler(){return cariOzetleri(data,month);}
 function filtered(){let rows=tab==='gider'?data.giderler.filter(r=>String(r.tarih||'').startsWith(month)).map(r=>({...r,kalem:r.baslik||r.aciklama||r.kategori,odenen:r.odendi===false?0:Number(r.tutar),durum:r.odendi===true?'odendi':r.odendi===false?'bekliyor':'tanimsiz'})):tab==='tahsilat'?data.gelirler.filter(r=>String(r.tarih||'').startsWith(month)):tab==='cari'?cariler():data.satirlar;
 return sirala(rows.filter(r=>(!search||[r.ogrenci,r.veli,r.kalem,r.sinif,r.kategori,r.yontem].join(' ').toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr')))&&(!sinif||r.sinif===sinif)&&(!status||(status==='gecikmis'?r.gecikmis:status==='buay'?(tab==='cari'?r.buay>0:r.kalan>0&&String(r.vade).startsWith(month)):status==='acik'?r.kalan>0:r.durum===status))),sort,direction);}
 function columns(){return tab==='gider'?[['tarih','Tarih'],['kalem','Gider'],['kategori','Kategori'],['tutar','Tutar'],['durum','Durum']]:tab==='tahsilat'?[['tarih','Tahsilat tarihi'],['ogrenci','Öğrenci'],['kalem','Ait olduğu ay / kalem'],['tutar','Tahsilat'],['yontem','Yöntem']]:tab==='cari'?[['ogrenci','Öğrenci'],['sinif','Sınıf'],['veli','Veli'],['beklenen','Toplam borç'],['odenen','Ödenen'],['geciken','Vadesi geçen'],['buay','Bu ay kalan'],['kalan','Toplam kalan'],['durum','Durum']]:[['ogrenci','Öğrenci'],['sinif','Sınıf'],['kalem','Ay / kalem'],['vade','Son ödeme'],['beklenen','Borç'],['odenen','Ödenen'],['kalan','Kalan'],['durum','Durum']];}
 function cell(r,k){if(['ogrenci','veli'].includes(k)&&r.ogrenciId)return `<button type="button" class="finance-person-link" data-student="${esc(r.ogrenciId)}">${esc(r[k]||'Hesabı aç')}</button>`;if(tab==='gider'&&k==='durum'&&r.durum==='tanimsiz')return '<span class="badge">Ödeme doğrulanmamış</span>';return ['tutar','beklenen','odenen','kalan','geciken','buay'].includes(k)?para(r[k]):k==='durum'?`<span class="badge ${r.gecikmis?'turuncu':r.durum==='odendi'?'yesil':''}">${esc(STATUS[r.durum]||r.durum)}${r.gecikmis&&r.durum==='kismi'?' · gecikti':''}</span>`:esc(r[k]||'—');}
 function table(){const rows=filtered(),cols=columns(),pages=Math.max(1,Math.ceil(rows.length/pageSize));page=Math.min(page,pages);const visible=rows.slice((page-1)*pageSize,page*pageSize);
 root.querySelector('#list').innerHTML=`<div class="list-summary"><span>${rows.length} kayıt · ${tab==='tahsilat'?'Tahsilat: '+para(toplam(rows,'tutar')):tab==='gider'?'Gider: '+para(toplam(rows,'tutar')):'Kalan: '+para(toplam(rows,'kalan'))}</span><label>Sayfada<select id="pageSize">${[10,25,50,100].map(n=>`<option ${n===pageSize?'selected':''}>${n}</option>`).join('')}</select></label></div><div class="scroll"><table><thead><tr>${cols.map(([k,t])=>`<th aria-sort="${sort===k?(direction==='asc'?'ascending':'descending'):'none'}"><button data-sort="${k}">${t} ${sort===k?(direction==='asc'?'↑':'↓'):'↕'}</button></th>`).join('')}${tab==='cari'?'<th>Detay</th>':''}</tr></thead><tbody>${visible.map(r=>`<tr>${cols.map(([k])=>`<td>${cell(r,k)}</td>`).join('')}${tab==='cari'?`<td><button data-student="${esc(r.ogrenciId)}" aria-label="${esc(r.ogrenci)} hesap detayı">Hesabı aç →</button></td>`:''}</tr>`).join('')||`<tr><td colspan="${cols.length+1}">Eşleşen kayıt bulunamadı.</td></tr>`}</tbody></table></div><div class="toolbar"><button id="previousPage" ${page===1?'disabled':''}>Önceki</button><span>Sayfa ${page} / ${pages}</span><button id="nextPage" ${page===pages?'disabled':''}>Sonraki</button></div>`;
 root.querySelector('#pageSize').onchange=e=>{pageSize=Number(e.target.value);page=1;table();};root.querySelector('#previousPage').onclick=()=>{page--;table();};root.querySelector('#nextPage').onclick=()=>{page++;table();};
 root.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{direction=sort===b.dataset.sort&&direction==='asc'?'desc':'asc';sort=b.dataset.sort;page=1;table();});root.querySelectorAll('[data-student]').forEach(b=>b.onclick=()=>student(b.dataset.student));
 root.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===tab)));}
 function detailDialog(title){const d=document.createElement('dialog');d.className='finance-detail';d.innerHTML=`<div class="detail-heading"><h2>${esc(title)}</h2><button aria-label="Kapat">Kapat</button></div><div class="detail-body"></div>`;root.append(d);d.querySelector('button').onclick=()=>d.close();d.onclose=()=>d.remove();d.showModal();return d;}
 function student(id){return hesapAc(root,ctx,{ogrenciId:id,donem:period,onDirtyClose:load});}
 function selectView(next){view=next;root.querySelectorAll('[data-section]').forEach(el=>el.hidden=el.dataset.section!==view);root.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));}
 function calendar(){const rows=sirala(data.satirlar.filter(r=>String(r.vade).startsWith(month)),'vade');const days=[...new Set(rows.map(r=>r.vade))];return `<h2>Finans takvimi · ${esc(month)}</h2><p class="muted">Ödeme planlarındaki vadeler. Yeşil: ödendi · Turuncu: gecikti.</p><div class="due-days">${days.map(day=>{const lines=rows.filter(r=>r.vade===day);return `<article class="card"><h3>${esc(day)}</h3><p>${para(toplam(lines,'kalan'))} kalan</p>${lines.map(r=>`<button class="due-item ${r.gecikmis?'turuncu':r.durum==='odendi'?'yesil':''}" data-due-student="${esc(r.ogrenciId)}"><b>${esc(r.ogrenci)}</b><small>${esc(r.kalem)} · ${para(r.kalan)} kalan · ${esc(STATUS[r.durum])}</small></button>`).join('')}</article>`;}).join('')||'<p>Bu ay için vade kaydı yok.</p>'}</div><p class="muted">Vadesi belirtilmemiş ${data.satirlar.filter(r=>!r.vade&&r.kalan>0).length} açık kalem takvimde gösterilemiyor.</p>`;}
 function render(){
 const due=data.satirlar.filter(r=>r.id===month),late=data.satirlar.filter(r=>r.gecikmis),cash=data.gelirler.filter(r=>String(r.tarih).startsWith(month)),expenses=data.giderler.filter(r=>String(r.tarih||'').startsWith(month));
 const pending=data.bildirimler.filter(b=>['bekliyor','beklemede'].includes(b.durum));
 const groups={};expenses.forEach(r=>{const k=r.kategori||'Sınıflandırılmamış';groups[k]=(groups[k]||0)+Number(r.tutar||0);});
 const fixed=expenses.filter(r=>r.tip==='sabit'),variable=expenses.filter(r=>r.tip==='degisken'),unclassified=expenses.filter(r=>!['sabit','degisken'].includes(r.tip));
 const enrolled=new Set(due.filter(r=>r.beklenen>0).map(r=>r.ogrenciId)).size;
 const be=unclassified.length||!expenses.length?{hazir:false,neden:'Başabaş için ayın giderlerini sabit / değişken olarak tamamlayın.'}:basabas({sabit:toplam(fixed,'tutar'),degisken:toplam(variable,'tutar'),ogrenci:enrolled,aylikGelir:toplam(due,'beklenen')});
 root.innerHTML=`<header><div class="muted">BİR ÇİÇEK KOLEJİ · FİNANS</div><h1>Muhasebe çalışma alanı</h1><p class="muted">${esc(period)} · Öğrenci ödeme planları ve tahsilatlar · Güncelleme: ${esc(new Date().toLocaleTimeString('tr-TR'))}</p></header>
 <nav class="finance-nav" aria-label="Muhasebe bölümleri">${[['panel','Finans paneli'],['accounts','Öğrenci carileri / Tahsilatlar'],['approvals','Ödeme bildirimleri'],['calendar','Finans takvimi'],['reports','Raporlar'],['bank','Banka mutabakatı'],['history','İşlem geçmişi']].map(([id,label])=>`<button data-view="${id}">${label}</button>`).join('')}</nav>
 <div class="toolbar"><label>Dönem<input id="period" value="${esc(period)}" pattern="[0-9]{4}-[0-9]{4}" size="10"></label><label>Ay<input id="month" type="month" value="${month}"></label><button id="refresh" class="primary">Yenile</button><button id="print">Yazdır / PDF</button></div>
 ${data.ogrenciler.some(o=>o.plan.uyarilar?.length)?`<div class="error"><b>Mutabakat gereken kayıtlar</b>${data.ogrenciler.flatMap(o=>(o.plan.uyarilar||[]).map(x=>`<p>${esc(o.ad)} · ${esc(x)}</p>`)).join('')}</div>`:''}<div class="cards" data-section="panel">${card('Döneme kayıtlı öğrenci',data.ogrenciler.length,'cari')}${card('Bu ay vadesi gelen kalan',para(toplam(data.satirlar.filter(r=>String(r.vade).startsWith(month)),'kalan')),'buay')}${card('Bu ay planlanan',para(toplam(due,'beklenen')),'cari')}${card('Bu ay tahsil edilen',para(toplam(cash,'tutar')),'tahsilat')}${card('Gecikmiş alacak',para(toplam(late,'kalan')),'gecikmis')}${card('Onay bekleyen',pending.length+' bildirim','onay')}${card('Bu ay kayıtlı gider',para(toplam(expenses,'tutar')),'gider')}${card('Dönem kalan alacak',para(toplam(data.satirlar,'kalan')),'acik')}</div>
 <section class="section" data-section="panel"><h2>Aylık tahsilat ve ödeme planı</h2>${chart()}</section><div class="charts" data-section="panel"><section class="section"><h2>Giderlerin dağılımı</h2>${bars(Object.entries(groups).map(([ad,tutar])=>({ad,tutar})).sort((a,b)=>b.tutar-a.tutar))}</section><section class="section"><h2>Başabaş senaryosu</h2>${be.hazir?`<strong>${be.adet} öğrenci</strong><p>${enrolled} öğrencinin bu ayki eğitim planı ve girilmiş giderler esas alınır.</p><label>Öğrenci sayısı<input type="number" id="scenario" min="0" value="${enrolled}"></label><p id="scenarioResult"></p><small>Gider kayıtlarının tamamlığı sonucu etkiler. Bu bir senaryodur; gerçekleşen kâr değildir.</small>`:`<p>${esc(be.neden)}</p>`}</section></div>
 <section class="section" data-section="reports"><h2>Aylık tahsilat ve ödeme planı</h2><button id="reportMatrix">Öğrenci bazında toplu rapor</button>${chart()}${trend()}</section>
 ${grafikRaporlar(data,month)}
 <section class="section" id="approvals" data-section="approvals"><h2>Ödeme bildirimleri</h2>${pending.map(b=>`<div class="payment card"><div><button type="button" class="finance-person-link" data-student="${esc(b.ogrenciId)}">${esc(b.ogrenciAd||data.ogrenciler.find(o=>o.id===b.ogrenciId)?.ad||'Öğrenci')}</button><small><button type="button" class="finance-person-link" data-student="${esc(b.ogrenciId)}">${esc(data.ogrenciler.find(o=>o.id===b.ogrenciId)?.veli||'Veli ödeme hesabı')}</button></small><small>${esc(b.kalemAd||b.ayAd||bildirimKalemi(b))} · ${para(b.bildirilenTutar??b.tutar)} · ${esc(b.odemeTarihi||'Tarih eksik')}</small><small>${esc(b.not||'')}</small>${!b.donem?'<small class="error">Dönem eksik: işlemden önce kayıt dönemi doğrulanmalı.</small>':''}${benzerBildirimler(b,data.bildirimler).length?`<small class="finance-warning" data-benzer-uyari style="color:#92541c">${esc(benzerBildirimUyarisi(benzerBildirimler(b,data.bildirimler)))}</small>`:''}</div><button data-review="${esc(b.id)}">İncele</button></div>`).join('')||'<p>Bekleyen bildirim yok.</p>'}</section>
 <section class="section" id="reconciliation" data-section="bank"></section><section class="section" data-section="history"><h2>İşlenmiş bildirimler</h2><p class="muted">İade veya hatalı onay düzeltmesi kayıt silmeden ters hareket oluşturur. Para transferi yapmaz.</p><div class="toolbar"><input id="historySearch" placeholder="Öğrenci veya kalem ara"><select id="historySort"><option value="date-desc">Tarih · yeniden eskiye</option><option value="date-asc">Tarih · eskiden yeniye</option><option value="name-asc">Öğrenci · A–Z</option><option value="name-desc">Öğrenci · Z–A</option><option value="amount-desc">Tutar · büyükten küçüğe</option><option value="amount-asc">Tutar · küçükten büyüğe</option></select></div><div id="history"></div></section><section class="section" data-section="calendar">${calendar()}</section><section class="section" data-section="accounts"><h2>Öğrenci hesapları ve hareketler</h2><div class="toolbar"><button data-tab="cari">Öğrenci carileri</button><button data-tab="kalem">Ay / kalem detayları</button><button data-tab="tahsilat">Tahsilatlar</button><button data-tab="gider">Giderler</button><button id="matrix">Aylık toplu rapor</button><button id="csv">CSV indir</button></div><div class="toolbar"><input id="search" placeholder="Öğrenci, veli veya kalem ara" value="${esc(search)}"><select id="status"><option value="">Tüm durumlar</option value="acik">Açık borçlar</option value="gecikmis">Gecikenler</option value="kismi">Kısmi ödemeler</option value="odendi">Ödenenler</option></select><select id="class"><option value="">Tüm sınıflar</option>${[...new Set(data.ogrenciler.map(o=>o.sinif))].filter(Boolean).sort().map(s=>`<option>${esc(s)}</option>`).join('')}</select></div><div id="list"></div></section>
 <p class="muted">Tarihsiz eski tahsilatlar aylık nakit grafiğine eklenmez (${data.gelirler.filter(r=>!r.tarih).length} kayıt). Geçmiş borçlar için ilgili dönemi seçebilirsiniz. Gider toplamı, ödeme durumu henüz doğrulanmamış kayıtları da kapsar.</p>`;
 mutabakatEkrani(root.querySelector('#reconciliation'),ctx,data);
 selectView(view);root.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>selectView(b.dataset.view));root.querySelectorAll('[data-due-student]').forEach(b=>b.onclick=()=>student(b.dataset.dueStudent));
 history();root.querySelector('#historySearch').oninput=history;root.querySelector('#historySort').onchange=history;
 table();root.querySelector('#status').value=status;root.querySelector('#class').value=sinif;
 root.querySelector('#search').oninput=e=>{search=e.target.value;page=1;table();};root.querySelector('#status').onchange=e=>{status=e.target.value;page=1;table();};root.querySelector('#class').onchange=e=>{sinif=e.target.value;page=1;table();};
 root.querySelector('#refresh').onclick=()=>{const p=root.querySelector('#period').value;if(!/^\d{4}-\d{4}$/.test(p))return alert('Dönemi 2026-2027 biçiminde girin.');period=p;month=root.querySelector('#month').value||bugun().slice(0,7);load();};root.querySelector('#month').onchange=e=>{month=e.target.value||bugun().slice(0,7);render();};
 root.querySelector('#print').onclick=()=>window.print();root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;page=1;status='';sinif='';root.querySelector('#status').value='';root.querySelector('#class').value='';sort=tab==='cari'?'ogrenci':'tarih';direction='asc';table();});
 root.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>{const t=b.dataset.card;if(t==='onay'){selectView('approvals');root.querySelector('#approvals').scrollIntoView();return;}selectView('accounts');page=1;search='';sinif='';root.querySelector('#search').value='';root.querySelector('#class').value='';tab=['gider','tahsilat'].includes(t)?t:'cari';sort=tab==='cari'?'ogrenci':'tarih';status=['acik','gecikmis','buay'].includes(t)?t:'';root.querySelector('#status').value=status;table();root.querySelector('#list').scrollIntoView();});
 root.querySelector('#csv').onclick=()=>download(filtered(),columns());root.querySelector('#matrix').onclick=matrix;root.querySelector('#reportMatrix').onclick=matrix;
 root.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>review(b.dataset.review));
 if(be.hazir){const calc=()=>{const n=Number(root.querySelector('#scenario').value);root.querySelector('#scenarioResult').textContent='Tahmini aylık faaliyet sonucu: '+para(n*be.katki-toplam(fixed,'tutar'));};root.querySelector('#scenario').oninput=calc;calc();}
 }
 function chart(){
 const months=[...new Set(data.satirlar.map(r=>r.id).filter(k=>/^\d{4}-\d{2}$/.test(k)))].sort();
 if(!months.length)return '';
 const vals=months.map(m=>({m,plan:toplam(data.satirlar.filter(r=>r.id===m),'beklenen'),cash:toplam(data.gelirler.filter(r=>String(r.tarih).startsWith(m)),'tutar')}));
 const max=Math.max(1,...vals.flatMap(r=>[r.plan,r.cash])),min=Math.min(0,...vals.map(r=>r.cash)),scale=150/(max-min),zero=25+max*scale,slot=660/months.length;
 return `<p class="muted">Açık yeşil: aylık plan · Koyu yeşil: net tahsilat · Turuncu: net ters kayıt</p><svg viewBox="0 0 720 220" role="img" aria-label="Aylık ödeme planı ve gerçekleşen tahsilat karşılaştırması"><line x1="40" y1="${zero}" x2="710" y2="${zero}" stroke="#b9cec0"/>${vals.map((r,i)=>{const x=45+i*slot,w=slot*.32;return `<g><title>${r.m}: plan ${para(r.plan)}, tahsilat ${para(r.cash)}</title><rect x="${x}" y="${zero-r.plan*scale}" width="${w}" height="${r.plan*scale}" fill="#b6d9c2"/><rect x="${x+w}" y="${zero-Math.max(0,r.cash)*scale}" width="${w}" height="${Math.abs(r.cash)*scale}" fill="${r.cash<0?'#c87828':'#245840'}"/><text x="${x}" y="200" font-size="10">${r.m.slice(2)}</text></g>`;}).join('')}</svg>`;
 }
 function trend(){const months=[...new Set(data.satirlar.map(r=>r.id).filter(k=>/^\d{4}-\d{2}$/.test(k)))].sort();return `<div class="scroll"><table><thead><tr><th>Ay</th><th>Planlanan</th><th>O aya işlenen</th><th>Kalan</th><th>Ay içinde tahsil</th></tr></thead><tbody>${months.map(m=>{const r=data.satirlar.filter(r=>r.id===m);return `<tr><td>${esc(m)}</td><td>${para(toplam(r,'beklenen'))}</td><td>${para(toplam(r,'odenen'))}</td><td>${para(toplam(r,'kalan'))}</td><td>${para(toplam(data.gelirler.filter(g=>String(g.tarih).startsWith(m)),'tutar'))}</td></tr>`;}).join('')}</tbody></table></div>`;}
 function matrix(){const months=[...new Set(data.satirlar.map(r=>r.id).filter(k=>/^\d{4}-\d{2}$/.test(k)))].sort(),extras=[...new Set(data.satirlar.filter(r=>r.id.startsWith('diger-')).map(r=>r.id))];
 const cols=[['ogrenci','Öğrenci'],['sinif','Sınıf'],['veli','Veli'],['beklenen','Toplam plan'],['odenen','Ödenen'],['kalan','Toplam kalan'],...extras.map(k=>[k,(data.satirlar.find(r=>r.id===k)?.ad||k)+' kalan']),...months.map(m=>[m,m+' kalan'])];
 const rows=data.ogrenciler.map(o=>({ogrenci:o.ad,sinif:o.sinif,veli:o.veli,beklenen:o.plan.toplam,odenen:o.plan.odenen,kalan:o.plan.kalan,...Object.fromEntries([...extras,...months].map(k=>[k,toplam(o.plan.satirlar.filter(r=>r.id===k),'kalan')]))}));
 const d=detailDialog('Aylık toplu rapor · '+period),body=d.querySelector('.detail-body');let term='',key='ogrenci',dir='asc';body.innerHTML='<div class="toolbar"><label>Öğrenci, veli, sınıf ara<input id="reportSearch"></label><button id="reportCSV">CSV indir</button></div><div id="reportTable"></div>';
 const draw=()=>{const selected=sirala(rows.filter(r=>[r.ogrenci,r.veli,r.sinif].join(' ').toLocaleLowerCase('tr').includes(term)),key,dir);body.querySelector('#reportTable').innerHTML=`<p>${selected.length} öğrenci · Ek kalemler ve aylar kalan borcu gösterir.</p><div class="scroll"><table><thead><tr>${cols.map(([k,label])=>`<th aria-sort="${key===k?(dir==='asc'?'ascending':'descending'):'none'}"><button data-report-sort="${k}">${esc(label)} ↕</button></th>`).join('')}</tr></thead><tbody>${selected.map(r=>`<tr>${cols.map(([k],i)=>`<td>${i<3?esc(r[k]):para(r[k])}</td>`).join('')}</tr>`).join('')}</tbody><tfoot><tr>${cols.map(([k],i)=>`<td>${i===0?'Genel toplam':i<3?'':para(toplam(selected,k))}</td>`).join('')}</tr></tfoot></table></div>`;body.querySelectorAll('[data-report-sort]').forEach(b=>b.onclick=()=>{dir=key===b.dataset.reportSort&&dir==='asc'?'desc':'asc';key=b.dataset.reportSort;draw();});body.querySelector('#reportCSV').onclick=()=>download(selected,cols);};body.querySelector('#reportSearch').oninput=e=>{term=e.target.value.toLocaleLowerCase('tr');draw();};draw();}
 function download(rows,cols){const quote=v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"';const csv='\uFEFF'+[cols.map(c=>quote(c[1])).join(';'),...rows.map(r=>cols.map(([k])=>quote(r[k])).join(';'))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`BirCicek-${tab}-${period}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function history(){
  const term=root.querySelector('#historySearch').value.toLocaleLowerCase('tr'),[key,dir]=root.querySelector('#historySort').value.split('-');
  const rows=data.bildirimler.filter(b=>!['bekliyor','beklemede'].includes(b.durum)).map(b=>({...b,name:b.ogrenciAd||'',date:b.odemeTarihi||'',amount:Number(b.bildirilenTutar??b.tutar)||0})).filter(b=>[b.name,b.kalemAd||b.ayAd||bildirimKalemi(b)].join(' ').toLocaleLowerCase('tr').includes(term));
  const labels={onaylandi:'Onaylandı',onayli:'Onaylandı',reddedildi:'Reddedildi',ret:'Reddedildi',kismi_iade:'Kısmen iade edildi',iade_edildi:'İade kaydedildi',geri_alindi:'Hatalı onay geri alındı'};
  root.querySelector('#history').innerHTML=sirala(rows,key,dir).map(b=>`<div class="payment card"><div><button type="button" class="finance-person-link" data-student="${esc(b.ogrenciId)}">${esc(b.name||'Ödeme hesabı')}</button><small>${esc(b.kalemAd||b.ayAd||bildirimKalemi(b))} · ${para(b.amount)} · ${esc(b.date)}</small><small>${esc(labels[b.durum]||b.durum)}</small></div>${['onaylandi','kismi_iade'].includes(b.durum)&&b.tahsilatIslendi?`<button data-reverse="${esc(b.id)}">İade / düzeltme</button>`:''}</div>`).join('')||'<p>İşlenmiş bildirim bulunmuyor.</p>';
  root.querySelector('#history').querySelectorAll('[data-student]').forEach(btn=>btn.onclick=()=>student(btn.dataset.student));
  root.querySelectorAll('[data-reverse]').forEach(b=>b.onclick=()=>reverse(b.dataset.reverse));
 }
 function reverse(id){
  const b=data.bildirimler.find(b=>b.id===id),remaining=Number(b.bildirilenTutar??b.tutar)-Number(b.iadeToplami||0),operationId='ters_'+crypto.randomUUID(),d=document.createElement('dialog');
  d.innerHTML=`<h2>Tahsilat iadesi / düzeltmesi</h2><p>${esc(b.ogrenciAd)} · ${esc(b.kalemAd||bildirimKalemi(b))} · ${para(b.bildirilenTutar??b.tutar)}</p><p>Girilen tutar ters kayıtla geri alınır ve ilgili borç bu tutar kadar yeniden açılır. İşlem para transferi yapmaz. Hatalı onay düzeltmesi kalan tahsilatın tamamına uygulanır.</p><form><label>İşlem<select name="type"><option value="duzeltme">Hatalı onayı düzelt</option><option value="iade">Yapılmış iadeyi kaydet</option></select></label><label>İade / düzeltme tutarı<input name="amount" type="number" step="0.01" min="0.01" max="${remaining}" value="${remaining}" required></label><label>İşlem tarihi<input name="date" type="date" min="${esc(b.odemeTarihi)}" max="${bugun()}" value="${bugun()}" required></label><label>Açıklama<textarea name="reason" minlength="5" maxlength="1000" required></textarea></label><label><input name="confirm" type="checkbox" required> Tutarı ve borcun yeniden açılacağını kontrol ettim.</label><p class="error" hidden></p><div class="toolbar"><button type="submit">Ters kaydı oluştur</button><button type="button" id="cancel">Vazgeç</button></div></form>`;
  root.append(d);d.showModal();d.onclose=()=>d.remove();d.querySelector('#cancel').onclick=()=>d.close();
  d.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);d.querySelectorAll('button').forEach(b=>b.disabled=true);try{await tahsilatiGeriAl({...ctx,id,tarih:f.get('date'),neden:f.get('reason'),tur:f.get('type'),tutar:Number(f.get('amount')),islemId:operationId});d.close();await load();}catch(err){const error=d.querySelector('.error');error.hidden=false;error.textContent=err.message;d.querySelectorAll('button').forEach(b=>b.disabled=false);}};
 }
 function review(id){const b=data.bildirimler.find(x=>x.id===id);if(b)return odemeKontrolAc(root,ctx,{bildirim:b,donem:period,onDone:load,onAccount:student});}
 await load();
}
