import {ODEME_HESABI} from './account.js';
import {esc,para,bugun,kartOzeti,odemePlani,bildirimKalemi,sirala} from './core.js';
const statuses={odendi:'Ödendi',kismi:'Kısmen ödendi',gecikmis:'Gecikti',bekliyor:'Ödenmedi',tanimsiz:'Tanımlanmamış'};
export async function veliEkrani(root,ctx){
 root.classList.add('finans-app');let selected=ctx.ogrenciler[0]?.id,period=ctx.donem,request=0;
 const {fb,db}=ctx;
 async function load(){root._financeUnsubscribe?.();root._financeUnsubscribe=null;const token=++request;root.innerHTML='<p>Ödeme kayıtları yükleniyor…</p>';try{
 if(!selected){root.textContent='Hesabınıza bağlı öğrenci bulunamadı.';return;}
 const [snap,periods,ns]=await Promise.all([fb.getDoc(fb.doc(db,'ogrenciler',selected,'donemler',period)),fb.getDocs(fb.collection(db,'ogrenciler',selected,'donemler')),fb.getDocs(fb.query(fb.collection(db,'odemeBildirimleri'),fb.where('ogrenciId','==',selected),fb.where('veliEmail','==',ctx.email.toLowerCase())))]);
 if(token!==request)return;
 const v=snap.exists()?snap.data():null,oz=kartOzeti(v),p=odemePlani(v),notes=ns.docs.map(d=>({id:d.id,...d.data()})).filter(n=>n.donem===period),pending=notes.filter(n=>['bekliyor','beklemede'].includes(n.durum));
 const previous=periods.docs.filter(d=>d.id<ctx.donem).map(d=>({id:d.id,p:odemePlani(d.data())})).filter(d=>d.p.kalan>0);
 const cardColor=previous.length?'turuncu':oz.renk;
 root.innerHTML=`<h1>Ödemelerim</h1><div class="toolbar"><label>Çocuğum<select id="child">${ctx.ogrenciler.map(o=>`<option value="${esc(o.id)}">${esc(o.ogrenciAdSoyad||o.ad||o.id)}</option>`).join('')}</select></label><label>Dönem<select id="period">${[...new Set([ctx.donem,...periods.docs.map(d=>d.id)])].sort().reverse().map(d=>`<option>${esc(d)}</option>`).join('')}</select></label><button id="refresh">Yenile</button></div>
 ${previous.length?`<div class="card turuncu"><strong>Geçmiş dönemden açık ödeme var</strong>${previous.map(d=>`<p><button data-period="${esc(d.id)}">${esc(d.id)} · ${para(d.p.kalan)} kalan</button></p>`).join('')}</div>`:''}
 <div class="card ${cardColor}"><strong style="font-size:20px">${esc(oz.baslik)}</strong>${oz.secilen?.kalan>0?'<button class="primary" id="first">Ödeme Bildir</button>':''}${oz.ekler.map(r=>`<p>${esc(r.ad)}: <b>${statuses[r.durum]}</b></p>`).join('')}</div>
 <div class="cards"><div class="card">Toplam plan<strong>${para(p.toplam)}</strong></div><div class="card">Doğrulanan ödeme<strong>${para(p.odenen)}</strong></div><div class="card">Kalan<strong>${para(p.kalan)}</strong></div></div>
 <p class="muted">Ödeme bildirimi, muhasebe doğrulamasından sonra borcunuza işlenir. Eski açık aylar aşağıda korunur.</p>
 <div class="toolbar"><select id="filter"><option value="all">Tüm ödemeler</option><option value="open">Açık ödemeler</option><option value="paid">Ödenenler</option></select><select id="paymentSort"><option value="order-asc">Plan sırası · eskiden yeniye</option><option value="order-desc">Plan sırası · yeniden eskiye</option><option value="name-asc">Kalem · A–Z</option><option value="name-desc">Kalem · Z–A</option><option value="balance-desc">Kalan · büyükten küçüğe</option><option value="balance-asc">Kalan · küçükten büyüğe</option></select></div>
 <div id="rows">${p.satirlar.map((r,index)=>{const n=pending.find(n=>bildirimKalemi(n)===r.id);return `<div class="card payment ${r.gecikmis?'turuncu':r.durum==='odendi'?'yesil':''}" data-order="${index}" data-name="${esc(r.ad)}" data-balance="${r.kalan}" data-open="${r.kalan>0}"><div><b>${esc(r.ad)}</b><small>${statuses[r.durum]}${r.gecikmis&&r.durum==='kismi'?' · gecikti':''}${r.vade?' · Son ödeme '+esc(r.vade):''}</small><small>Plan: ${para(r.beklenen)} · Ödenen: ${para(r.odenen)} · Kalan: ${para(r.kalan)}</small>${n?'<p class="status">Bildiriminiz kontrol ediliyor</p>':''}${r.record.hareketler?.length?`<details><summary>Ödeme hareketleri</summary>${sirala(r.record.hareketler,'tarih','desc').map(h=>`<p>${esc(h.tarih||'Eski kayıt · tarih belirtilmemiş')} · ${para(h.tutar)} · ${esc(h.tur==='iade'?'İade':h.tur==='duzeltme'?'Onay düzeltmesi':h.yontem||'Tahsilat')}</p>`).join('')}</details>`:''}</div>${r.kalan>0&&!n?`<button data-pay="${esc(r.id)}">Ödeme Bildir</button>`:''}</div>`;}).join('')||'<p>Ödeme planı henüz oluşturulmamış.</p>'}</div>
 <section class="section"><h2>Ödeme hesabı</h2><p>${esc(ODEME_HESABI.banka)} · ${esc(ODEME_HESABI.hesapSahibi)}</p><p style="overflow-wrap:anywhere">${esc(ODEME_HESABI.iban)}</p><button id="ibanCopy">IBAN kopyala</button><small>Açıklamaya öğrencinin adını ve ödemenin ait olduğu ayı yazabilirsiniz.</small></section><section class="section"><h2>Bildirim geçmişi</h2>${notes.sort((a,b)=>String(b.odemeTarihi||'').localeCompare(String(a.odemeTarihi||''))).map(n=>`<p>${esc(n.kalemAd||n.ayAd||bildirimKalemi(n))} · ${para(n.bildirilenTutar??n.tutar)} · ${esc(['onayli','onaylandi'].includes(n.durum)?'Onaylandı':['ret','reddedildi'].includes(n.durum)?'Reddedildi':n.durum==='iade_edildi'?'İade kaydedildi':n.durum==='geri_alindi'?'Onay geri alındı':'Kontrol ediliyor')}</p>`).join('')||'<p>Bildirim bulunmuyor.</p>'}</section>`;
 root.querySelector('#ibanCopy').onclick=async e=>{try{await navigator.clipboard.writeText(ODEME_HESABI.iban);e.target.textContent='Kopyalandı';}catch(_){e.target.textContent='Kopyalanamadı; IBAN’ı seçerek kopyalayabilirsiniz.';}};
 if(fb.onSnapshot){const before=JSON.stringify(v);const unsubPeriod=fb.onSnapshot(fb.doc(db,'ogrenciler',selected,'donemler',period),newSnap=>{if(token!==request||!root.isConnected){root._financeUnsubscribe?.();return;}if(JSON.stringify(newSnap.exists()?newSnap.data():null)!==before){if(root.querySelector('dialog[open]'))root.querySelector('#refresh').textContent='Yeni ödeme durumu var · Yenile';else load();}},()=>{const b=root.querySelector('#refresh');if(b)b.textContent='Canlı bağlantı kesildi · Yenile';});
 const noteKey=docs=>JSON.stringify(docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>a.id.localeCompare(b.id))),beforeNotes=noteKey(ns.docs);
 const unsubNotes=fb.onSnapshot(fb.query(fb.collection(db,'odemeBildirimleri'),fb.where('ogrenciId','==',selected),fb.where('veliEmail','==',ctx.email.toLowerCase())),snapshot=>{if(token!==request||!root.isConnected){unsubNotes();return;}if(noteKey(snapshot.docs)!==beforeNotes){if(root.querySelector('dialog[open]'))root.querySelector('#refresh').textContent='Yeni bildirim durumu var · Yenile';else load();}},()=>{const b=root.querySelector('#refresh');if(b)b.textContent='Bildirim bağlantısı kesildi · Yenile';});
 root._financeUnsubscribe=()=>{unsubPeriod();unsubNotes();};}
 root.querySelector('#child').value=selected;root.querySelector('#period').value=period;
 root.querySelector('#child').onchange=e=>{selected=e.target.value;load();};root.querySelector('#period').onchange=e=>{period=e.target.value;load();};root.querySelector('#refresh').onclick=load;root.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{period=b.dataset.period;load();});root.querySelector('#filter').onchange=e=>root.querySelectorAll('[data-open]').forEach(el=>el.hidden=e.target.value==='open'?el.dataset.open!=='true':e.target.value==='paid'?el.dataset.open==='true':false);
 root.querySelector('#paymentSort').onchange=e=>{const [key,dir]=e.target.value.split('-'),rows=[...root.querySelectorAll('#rows [data-order]')].map(el=>({el,order:Number(el.dataset.order),balance:Number(el.dataset.balance),name:el.dataset.name}));for(const r of sirala(rows,key,dir))root.querySelector('#rows').append(r.el);};
 root.querySelectorAll('[data-pay]').forEach(b=>b.onclick=()=>pay(p.satirlar.find(r=>r.id===b.dataset.pay)));
 const first=root.querySelector('#first');if(first)first.onclick=()=>{const row=root.querySelector(`[data-pay="${oz.secilen.id}"]`);if(row)row.click();else root.querySelector('#rows').scrollIntoView();};
 }catch(e){if(token!==request)return;root.innerHTML=`<div class="error">Ödeme bilgileri okunamadı. Borç durumu gösterilemiyor.<p>${esc(e.message)}</p><button id="retry">Yeniden dene</button></div>`;root.querySelector('#retry').onclick=load;}}
 function pay(r){const d=document.createElement('dialog');d.innerHTML=`<h2>${esc(r.ad)} · Ödeme Bildir</h2><p>Kalan: ${para(r.kalan)}</p><form><label>Ödediğiniz tutar<input name="amount" type="number" step="0.01" min="0.01" max="${r.kalan}" value="${r.kalan}" required></label><label>Ödeme tarihi<input name="date" type="date" max="${bugun()}" value="${bugun()}" required></label><label>Yöntem<select name="method"><option value="havale">Havale / EFT</option><option value="nakit">Nakit</option><option value="kart">Kart</option></select></label><label>Not<input name="note" maxlength="1000"></label><p class="error" hidden></p><div class="toolbar"><button type="submit" class="primary">Bildirimi gönder</button><button type="button" id="cancel">Vazgeç</button></div></form>`;root.append(d);d.showModal();d.querySelector('#cancel').onclick=()=>d.close();d.onclose=()=>d.remove();const ref=fb.doc(fb.collection(db,'odemeBildirimleri'));d.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),amount=Number(f.get('amount'));if(!Number.isFinite(amount)||amount<=0||amount>r.kalan)return;d.querySelectorAll('button').forEach(b=>b.disabled=true);try{const o=ctx.ogrenciler.find(o=>o.id===selected);await fb.setDoc(ref,{ogrenciId:selected,ogrenciAd:o.ogrenciAdSoyad||o.ad||'',sinif:o.sinif||'',donem:period,kalemTipi:r.id.startsWith('diger-')||r.id==='__onOdeme'?r.id:'aidat-'+r.id,kalemAd:r.ad,ayKod:r.id,tutar:amount,bildirilenTutar:amount,odemeTarihi:f.get('date'),odemeYontemi:f.get('method'),not:f.get('note'),durum:'bekliyor',veliEmail:ctx.email.toLowerCase(),olusturuldu:fb.serverTimestamp()});d.close();await load();}catch(err){const x=d.querySelector('.error');x.hidden=false;x.textContent='Bildirim gönderilemedi: '+err.message;d.querySelectorAll('button').forEach(b=>b.disabled=false);}};}
 await load();
}
