// Cloud-browser-only synthetic QA. All routes are fulfilled locally or aborted.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
let playwright;try{playwright=require('playwright')}catch(_){playwright=require('/opt/codex/cua_node/lib/node_modules/playwright')}
const root=path.resolve(__dirname,'..'),output=path.resolve(process.env.GALLERY_QA_OUTPUT||path.join(root,'..','qa-output','gallery-approval'));
(async()=>{
 const {gallerySource,navigationSource,galleryControls,lightboxMarkup,selectedStyles,exposeGallery,media}=await import('./galeri-onay-fixture.mjs');
 const helper=fs.readFileSync(path.join(root,'js/galeri-onay-canli.js'),'utf8').replaceAll('export ','')+'\n'+fs.readFileSync(path.join(root,'js/galeri-klasorleri.js'),'utf8').replaceAll('export ','');
 const bootstrap=`
 window.state={currentUser:{uid:'synthetic-admin',email:'synthetic-admin@example.test'},rol:'mudur',personel:{durum:'aktif'},galeriOturumSurumu:1};
 window.rows=${JSON.stringify([media('portal'),media('legacy',{durum:'onayBekliyor'}),media('processed',{durum:'onaylandi'})])};window.events=[];window.listeners=[];window.delayed=new Map();window.toasts=[];
 const db={},snapshot=items=>({docs:items.map(row=>({id:row.id,data:()=>row})),metadata:{fromCache:false}});
 const fb={collection:(_db,name)=>name,where:(...args)=>args,query:(...args)=>args,onSnapshot:(q,o,next,error)=>{const entry={next,error,stopped:false};listeners.push(entry);return()=>entry.stopped=true;},getDocs:async()=>snapshot(rows),doc:(_db,collection,id)=>({collection,id}),getDoc:async ref=>{events.push(['read',ref.id]);if(delayed.has(ref.id))return await delayed.get(ref.id).promise;const row=rows.find(x=>x.id===ref.id);return{id:ref.id,exists:()=>!!row,data:()=>row};},updateDoc:async()=>{events.push(['write']);throw Error('Unexpected synthetic write');}};
 const {collection,where,query,getDocs,doc,getDoc,updateDoc}=fb;
 window.PortalAPI={state,fb,db};let currentUser=state.currentUser,aktifKullaniciRol=state.rol,isAdmin=false,AKTIF_DONEM='2026-2027';
 const createGalleryFolderView=()=>({reset(){},render(){throw Error('Not part of approval fixture')}});
 const escapeHtml=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const showToast=(text,type)=>toasts.push({text,type});
 const MODUL_HARITASI={galeri:{tablar:['galeri'],varsayilan:'galeri'},profilim:{tablar:['profilim'],varsayilan:'profilim'}};let aktifModul='galeri';const sekmeyeErisim=()=>true,mesajlasmaDurdur=()=>{},egitimArkaPlanCalismasiniDurdur=()=>{},adminHomeArkaPlanCalismasiniDurdur=()=>{};
 `;
 const utilities=`window.emit=(items=rows,cache=false,index=listeners.length-1)=>listeners[index].next({...snapshot(items),metadata:{fromCache:cache}});window.fail=()=>listeners.at(-1).error({code:'permission-denied'});window.delay=id=>{let release;const promise=new Promise(resolve=>release=resolve);delayed.set(id,{promise,release});};window.release=id=>{const row={id,durum:'beklemede',dosyaTipi:'foto',bunnyUrl:'https://synthetic-media.test/'+id+'.svg'};delayed.get(id).release({id,exists:()=>true,data:()=>row});};window.fixtureReady=true;`;
 const html=`<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box}body{margin:0;padding:16px;font-family:Arial,sans-serif;background:#faf8fc;color:#17212b}.tab-panel{display:none}.tab-panel.active{display:block}.tabs{display:flex;gap:8px;margin-bottom:14px}.tabs .tab{padding:8px}h1{font-size:22px}.fixture-label{font-size:11px;color:#657080} ${selectedStyles}</style></head><body><div class="fixture-label">SENTETİK QA · Gerçek kullanıcı veya medya yok</div><h1>Galeri onayı <span id="galeriMenuOnayRozet"></span></h1><nav class="tabs"><button class="tab active" data-tab="galeri">Galeri</button><button class="tab" data-tab="profilim">Profilim</button></nav><section class="tab-panel active" id="tab-galeri">${galleryControls}<div id="galeriListesi"></div></section><section class="tab-panel" id="tab-profilim">Sentetik profil</section>${lightboxMarkup}<script>${helper}\n${bootstrap}\n${gallerySource}\n${navigationSource}\n${exposeGallery}\n${utilities}</script></body></html>`;
 fs.mkdirSync(output,{recursive:true});new (require('node:vm').Script)(helper+'\n'+bootstrap+'\n'+gallerySource+'\n'+navigationSource+'\n'+exposeGallery+'\n'+utilities);if(process.env.GALLERY_QA_PREPARE_ONLY==='1'){fs.writeFileSync(path.join(output,'synthetic-fixture.html'),html);console.log('Synthetic fixture compiled: '+output);return;}const browser=await playwright.chromium.launch({headless:true,executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const summary=[];
 try{for(const viewport of [{width:1280,height:900},{width:320,height:740}]){
 const page=await browser.newPage({viewport}),errors=[],blocked=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async route=>{const url=new URL(route.request().url());if(url.origin==='http://approval-fixture.test'&&url.pathname==='/')return route.fulfill({contentType:'text/html',body:html});if(url.origin==='https://synthetic-media.test')return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400"><rect width="400" height="400" fill="#b5c7eb"/><circle cx="200" cy="160" r="80" fill="#7b94ca"/><text x="200" y="290" text-anchor="middle" font-family="Arial" font-size="24" fill="#304568">Sentetik Medya</text></svg>'});blocked.push(route.request().url());return route.abort();});
 const reset=async()=>{await page.goto('http://approval-fixture.test/');await page.waitForFunction(()=>window.fixtureReady);};await reset();
 await page.locator('[data-galeri-filter="onayBekliyor"]').click();assert.match(await page.locator('#galeriListesi').innerText(),/yükleniyor/);await page.evaluate(()=>emit());assert.equal(await page.locator('#galeriOnayBekleyenRozet').innerText(),'2');assert.equal(await page.locator('#galeriListesi [onclick^="acGaleriLightbox"]').count(),2);
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'pending queue must fit viewport');await page.screenshot({path:path.join(output,`pending-${viewport.width}.png`),fullPage:true});
 await page.evaluate(()=>fail());assert.match(await page.locator('#galeriListesi').innerText(),/yüklenemedi/);assert(!/Henüz içerik yok/.test(await page.locator('#galeriListesi').innerText()));await page.screenshot({path:path.join(output,`error-${viewport.width}.png`),fullPage:true});
 await page.getByRole('button',{name:'Yeniden dene',exact:true}).click();assert.equal(await page.evaluate(()=>listeners.length),2);assert.equal(await page.evaluate(()=>listeners[0].stopped),true);await page.evaluate(()=>emit([]));assert.match(await page.locator('#galeriListesi').innerText(),/Henüz içerik yok/);
 await page.evaluate(()=>fixtureAPI.notice({tip:'galeri',hedefSayfa:'galeri-onay.html?medya=legacy'}));assert.equal(await page.locator('#galeriLightbox').evaluate(e=>e.classList.contains('active')),true);assert.match(await page.locator('#galeriLightboxIcerik img').getAttribute('src'),/legacy.svg/);await page.screenshot({path:path.join(output,`deep-link-${viewport.width}.png`),fullPage:true});
 await page.locator('#galeriLightbox button').filter({hasText:'×'}).click();assert.equal(await page.locator('#galeriLightbox').evaluate(e=>e.classList.contains('active')),false);
 for(const action of ['close','new-card','filter','module-return','tab-return','logout']){
 await reset();await page.evaluate(()=>{galeriFilter('onayBekliyor');emit();delay('late');window.waiting=fixtureAPI.notice({tip:'galeri_onay',kaynakId:'late'});});
 await page.evaluate(action=>{if(action==='close')closeGaleriLightbox();if(action==='new-card')acGaleriLightbox('portal');if(action==='filter')galeriFilter('foto');if(action==='module-return'){modulSec('profilim');modulSec('galeri');}if(action==='tab-return'){document.querySelector('[data-tab="profilim"]').click();document.querySelector('[data-tab="galeri"]').click();}if(action==='logout'){state.currentUser=null;fixtureAPI.stop();}release('late');},action);await page.evaluate(()=>waiting);
 assert.equal(await page.evaluate(()=>fixtureAPI.read().active?.id||null),action==='new-card'?'portal':null,action+' stale opening');assert.equal(await page.evaluate(()=>fixtureAPI.read().items.some(x=>x.id==='late')),false);
 }
 await reset();await page.evaluate(()=>fixtureAPI.notice({tip:'galeri',hedefSayfa:'galeri-onay.html'}));assert.equal(await page.evaluate(()=>events.filter(x=>x[0]==='read').length),0);
 for(const id of ['processed','deleted']){await page.evaluate(id=>fixtureAPI.notice({tip:'galeri_onay',kaynakId:id}),id);assert.equal(await page.evaluate(()=>fixtureAPI.read().active),null);}
 assert.deepEqual(await page.evaluate(()=>events.filter(x=>x[0]==='write')),[]);assert.deepEqual(blocked,[]);assert.deepEqual(errors,[]);summary.push({viewport,cases:['both pending statuses','loading/error/empty distinction','retry','deep link','actual close','delayed close/card/filter/module/tab/logout','legacy no-id','processed/deleted no write','viewport overflow'],pageErrors:errors,unexpectedNetwork:blocked});await page.close();
 }
 fs.writeFileSync(path.join(output,'result.json'),JSON.stringify({passed:true,mode:'fully intercepted synthetic cloud browser',cases:summary},null,2));console.log('PASS synthetic desktop and 320px approval UI; screenshots: '+output);
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
